import { requireActiveGymContext } from "@/lib/server/gym-context";
import { createServerComponentSupabaseClient } from "@/lib/supabase/server";

export default async function AnnouncementsPage({ params }: { params: Promise<{ gymSlug: string }> }) {
  const { gymSlug } = await params; const { gym } = await requireActiveGymContext({ gymSlug });
  const supabase = await createServerComponentSupabaseClient(); const now = new Date().toISOString();
  const { data, error } = await supabase.from("announcements").select("id,title,body,priority,is_pinned,published_at,expires_at").eq("gym_id",gym.id).eq("status","published").is("archived_at",null).lte("published_at",now).or(`expires_at.is.null,expires_at.gt.${now}`).order("is_pinned",{ascending:false}).order("published_at",{ascending:false});
  return <div className="mx-auto max-w-4xl"><p className="app-eyebrow text-[var(--muted)]">Gym updates</p><h1 className="mt-3 text-4xl font-extrabold tracking-[-.035em]">Announcements</h1>{error ? <p className="mt-8 rounded-[var(--radius-lg)] bg-red-50 p-5 text-red-800">Announcements could not be loaded.</p> : data?.length ? <div className="mt-8 space-y-4">{data.map((item)=><article className="scroll-mt-6 rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface)] p-5" id={`announcement-${item.id}`} key={item.id}><div className="flex items-center gap-2"><h2 className="text-xl font-black">{item.title}</h2>{item.is_pinned?<span className="rounded-full bg-[var(--accent)] px-2 py-1 text-xs font-bold text-[var(--accent-foreground)]">Pinned</span>:null}{item.priority!=="normal"?<span className="rounded-full bg-red-100 px-2 py-1 text-xs font-bold text-red-800">{item.priority}</span>:null}</div><p className="mt-4 whitespace-pre-line leading-7">{item.body}</p><p className="mt-4 text-xs text-[var(--muted)]">Published {item.published_at ? new Date(item.published_at).toLocaleString("en-GB") : "now"}</p></article>)}</div>:<p className="mt-8 rounded-[var(--radius-lg)] bg-[var(--primary)]/5 p-5 text-[var(--muted)]">There are no current announcements.</p>}</div>;
}
