import { notFound } from "next/navigation";
import Link from "next/link";
import { WallForm } from "@/components/wall-form";
import { WallImageForm } from "@/components/wall-image-form";
import { archiveWallAction, bulkRouteAction } from "@/features/routes/actions";
import { requireActiveGymContext } from "@/lib/server/gym-context";
import { createServerComponentSupabaseClient } from "@/lib/supabase/server";

export default async function StaffRoutesPage({ params }: { params: Promise<{ gymSlug: string }> }) {
  const { gymSlug } = await params;
  const { gym } = await requireActiveGymContext({ gymSlug, allowedRoles: ["owner", "staff", "route_setter"] });
  const supabase = await createServerComponentSupabaseClient();
  if (gym.role === "staff") {
    const { data: membership } = await supabase.from("gym_memberships").select("staff_role_id").eq("id", gym.membershipId).single();
    const { data: role } = membership?.staff_role_id ? await supabase.from("staff_roles").select("capabilities").eq("id", membership.staff_role_id).single() : { data: null };
    if (!role?.capabilities.includes("routes.manage")) notFound();
  }
  const [{ data: walls }, { data: routes }] = await Promise.all([
    supabase.from("walls").select("id,wall_structure_id,name,description,sort_order,is_active,archived_at,width_metres,height_metres,climbing_angle_degrees,wall_images(id,storage_path,alt_text,width,height,version,is_current,archived_at)").eq("gym_id", gym.id).order("sort_order"),
    supabase.from("routes").select("id,wall_id,wall_image_id,name,colour,grade_system,grade,route_type,status,setter_id,set_on,retire_on,description,overlay,created_at,route_tags(tag),route_media(id)").eq("gym_id", gym.id).order("created_at", { ascending: false }),
  ]);
  const activeWalls = (walls ?? []).filter((wall) => wall.is_active && !wall.archived_at);
  const routeValues = (routes ?? []).map((route) => ({ ...route, route_type: route.route_type as "boulder" | "sport" | "top_rope" | "trad" | "training", status: route.status as "draft" | "published" | "retired" | "archived", tags: route.route_tags.map(({ tag }) => tag) }));
  const structuredFaceIds = new Set(activeWalls.filter(({ wall_structure_id }) => wall_structure_id).map(({ id }) => id));

  return <div className="mx-auto max-w-6xl">
    <p className="text-sm font-bold uppercase tracking-[0.2em] text-[var(--muted)]">Setting operations</p><div className="mt-3 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-4xl font-black">Faces and routes</h1><p className="mt-3 max-w-3xl text-[var(--muted)]">Routes attach to climbing faces. Current images power normalized overlays, while retiring routes preserves every ascent and historical record.</p></div>{gym.role === "owner" ? <Link className="rounded-xl border px-4 py-3 text-sm font-bold" href={`/g/${gym.slug}/staff/floorplan`}>Manage floorplan and faces</Link> : null}</div>
    <section className="mt-8"><h2 className="text-xl font-black">Face library</h2><div className="mt-4 grid gap-4 lg:grid-cols-2">{activeWalls.map((wall) => { const history = wall.wall_images.toSorted((a, b) => b.version - a.version); return <article className="rounded-2xl border border-[var(--border)] bg-white p-5" key={wall.id}>{wall.wall_structure_id ? <div><p className="text-xs font-bold uppercase tracking-[.16em] text-[var(--muted)]">Structured climbing face</p><h3 className="mt-1 text-xl font-black">{wall.name}</h3><p className="mt-2 text-sm text-[var(--muted)]">{wall.width_metres} × {wall.height_metres} m · {wall.climbing_angle_degrees}° from vertical</p><Link className="mt-4 inline-flex min-h-11 items-center rounded-full bg-black px-5 text-sm font-bold text-white" href={`/g/${gym.slug}/staff/floorplan/faces/${wall.id}`}>Create routes from holds</Link></div> : <WallForm gymSlug={gym.slug} wall={wall} />}<p className="mt-3 text-xs text-[var(--muted)]">{history.length ? `${history.length} image version${history.length === 1 ? "" : "s"} · current v${history.find((image) => image.is_current && !image.archived_at)?.version ?? "—"}` : "No image uploaded"}</p><WallImageForm gymSlug={gym.slug} wallId={wall.id} />{wall.wall_structure_id ? null : <form action={archiveWallAction} className="mt-3"><input name="gymSlug" type="hidden" value={gym.slug} /><input name="wallId" type="hidden" value={wall.id} /><button className="text-sm font-bold text-red-700">Archive legacy wall</button></form>}</article>; })}{activeWalls.length ? null : <p className="rounded-2xl bg-white p-5 text-sm text-[var(--muted)]">Create a wall structure and its first face before adding routes.</p>}</div></section>
    <section className="mt-10"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-black">Route library</h2><p className="mt-1 text-sm text-[var(--muted)]">Use a structured face to edit hold collections. Retired and archived routes remain historical.</p></div><form action={bulkRouteAction} className="flex gap-2" id="bulk-routes"><input name="gymSlug" type="hidden" value={gym.slug} /><button className="rounded-full bg-black px-4 py-2 text-sm font-bold text-white" name="operation" value="publish">Publish selected</button><button className="rounded-full border px-4 py-2 text-sm font-bold" name="operation" value="retire">Reset / retire selected</button></form></div><div className="mt-4 grid gap-3 md:grid-cols-2">{routeValues.map((route) => <article className="rounded-2xl border border-[var(--border)] bg-white p-5" key={route.id}><label className="flex items-center gap-2 text-sm font-bold"><input form="bulk-routes" name="routeIds" type="checkbox" value={route.id} /> Select · {route.status}</label><h3 className="mt-3 text-xl font-black">{route.name ?? `${route.colour} ${route.grade}`}</h3><p className="mt-1 text-sm text-[var(--muted)]">{route.grade_system} {route.grade} · {route.colour} · {route.route_media.length} media</p>{structuredFaceIds.has(route.wall_id) ? <Link className="mt-4 inline-flex min-h-11 items-center font-bold underline" href={`/g/${gym.slug}/staff/floorplan/faces/${route.wall_id}`}>Edit on wall canvas</Link> : <p className="mt-3 text-xs text-amber-800">Legacy image route; preserved for history.</p>}</article>)}{routeValues.length ? null : <p className="rounded-2xl bg-white p-5 text-sm text-[var(--muted)]">No routes yet. Open a structured face and select its holds.</p>}</div></section>
  </div>;
}
