import Image from "next/image";
import Link from "next/link";
import { AscentForm } from "@/components/ascent-form";
import { deleteAscentAction } from "@/features/ascents/actions";
import { requireActiveGymContext } from "@/lib/server/gym-context";
import { createServerComponentSupabaseClient } from "@/lib/supabase/server";

const outcomes = ["flash", "onsight", "redpoint", "repeat", "attempted", "project"] as const;
const visibilities = ["private", "gym", "public"] as const;
type Search = { outcome?: string; from?: string; to?: string; visibility?: string };

export default async function LogbookPage({ params, searchParams }: { params: Promise<{ gymSlug: string }>; searchParams: Promise<Search> }) {
  const [{ gymSlug }, search] = await Promise.all([params, searchParams]); const { gym } = await requireActiveGymContext({ gymSlug });
  const supabase = await createServerComponentSupabaseClient(); const { data: { user } } = await supabase.auth.getUser();
  let query = supabase.from("ascent_logs").select("id,route_id,session_id,session_date,ascent_type,attempts,notes,visibility,created_at,route_name_snapshot,route_colour_snapshot,route_grade_snapshot,route_grade_system_snapshot,wall_name_snapshot,ascent_media(id,storage_path,media_type)").eq("gym_id", gym.id).eq("profile_id", user?.id ?? "").is("deleted_at", null).order("session_date", { ascending: false }).order("created_at", { ascending: false });
  if (outcomes.includes(search.outcome as typeof outcomes[number])) query = query.eq("ascent_type", search.outcome as typeof outcomes[number]);
  if (visibilities.includes(search.visibility as typeof visibilities[number])) query = query.eq("visibility", search.visibility as typeof visibilities[number]);
  if (/^\d{4}-\d{2}-\d{2}$/.test(search.from ?? "")) query = query.gte("session_date", search.from as string);
  if (/^\d{4}-\d{2}-\d{2}$/.test(search.to ?? "")) query = query.lte("session_date", search.to as string);
  const [{ data: ascents }, { data: sessions }] = await Promise.all([query, supabase.from("climbing_sessions").select("id,session_date").eq("gym_id", gym.id).eq("profile_id", user?.id ?? "").order("session_date", { ascending: false }).limit(50)]);
  const routeIds = [...new Set((ascents ?? []).map(({ route_id }) => route_id))];
  const { data: liveRoutes } = routeIds.length ? await supabase.from("routes").select("id").eq("gym_id", gym.id).eq("status", "published").in("id", routeIds) : { data: [] };
  const live = new Set((liveRoutes ?? []).map(({ id }) => id));
  const media = await Promise.all((ascents ?? []).map(async (ascent) => ({ ...ascent, media: await Promise.all(ascent.ascent_media.map(async (item) => ({ ...item, url: (await supabase.storage.from("ascent-media").createSignedUrl(item.storage_path, 3600)).data?.signedUrl ?? null }))) })));
  // Server request time is the correct reference for the database's matching 30-day edit rule.
  // eslint-disable-next-line react-hooks/purity
  const editableAfter = Date.now() - 30 * 86_400_000;
  return <div className="mx-auto max-w-5xl"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[var(--muted)]">Training history</p><h1 className="mt-2 text-4xl font-black">Your logbook</h1><p className="mt-2 text-sm text-[var(--muted)]">Newest session first. You always retain access regardless of social privacy.</p></div><Link className="inline-flex min-h-12 items-center rounded-xl bg-black px-5 font-bold text-white" href={`/g/${gym.slug}/app/routes`}>Find a route to log</Link></div>
    <form className="mt-7 grid gap-3 rounded-2xl border bg-white p-4 sm:grid-cols-4"><label className="text-sm font-bold">Outcome<select className="mt-1 w-full rounded-lg border p-3 font-normal" defaultValue={search.outcome ?? ""} name="outcome"><option value="">All outcomes</option>{outcomes.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label className="text-sm font-bold">Privacy<select className="mt-1 w-full rounded-lg border p-3 font-normal" defaultValue={search.visibility ?? ""} name="visibility"><option value="">All privacy</option>{visibilities.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label className="text-sm font-bold">From<input className="mt-1 w-full rounded-lg border p-3 font-normal" defaultValue={search.from} name="from" type="date"/></label><label className="text-sm font-bold">To<input className="mt-1 w-full rounded-lg border p-3 font-normal" defaultValue={search.to} name="to" type="date"/></label><button className="min-h-12 rounded-xl border font-bold sm:col-span-4">Apply filters</button></form>
    <div className="mt-7 space-y-5">{media.map((ascent) => { const title = ascent.route_name_snapshot || `${ascent.route_colour_snapshot} ${ascent.route_grade_snapshot}`; const editable = new Date(ascent.created_at).getTime() >= editableAfter; return <article className="rounded-2xl border border-[var(--border)] bg-white p-5" key={ascent.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase text-[var(--muted)]">{ascent.session_date} · {ascent.wall_name_snapshot}</p><h2 className="mt-1 text-xl font-black">{live.has(ascent.route_id) ? <Link className="underline" href={`/g/${gym.slug}/app/routes/${ascent.route_id}`}>{title}</Link> : title}</h2><p className="mt-1 text-sm font-bold">{ascent.route_grade_system_snapshot} {ascent.route_grade_snapshot} · {ascent.ascent_type} · {ascent.attempts} attempt{ascent.attempts === 1 ? "" : "s"}</p></div><span className="rounded-full bg-stone-100 px-3 py-1 text-xs font-bold">{ascent.visibility}</span></div>{ascent.notes ? <p className="mt-4 whitespace-pre-wrap text-sm text-[var(--muted)]">{ascent.notes}</p> : null}<div className="mt-4 grid gap-3 sm:grid-cols-2">{ascent.media.map((item) => item.url ? item.media_type === "video" ? <video className="w-full rounded-xl" controls key={item.id} src={item.url}/> : <Image alt={`Media for ${title}`} className="h-auto w-full rounded-xl" height={700} key={item.id} src={item.url} unoptimized width={1000}/> : null)}</div>{editable ? <details className="mt-5 rounded-xl bg-stone-50 p-4"><summary className="cursor-pointer font-bold">Edit ascent</summary><div className="mt-4"><AscentForm gymSlug={gym.slug} routeId={ascent.route_id} sessions={sessions ?? []} value={ascent}/><form action={deleteAscentAction} className="mt-3"><input name="gymSlug" type="hidden" value={gym.slug}/><input name="routeId" type="hidden" value={ascent.route_id}/><input name="ascentId" type="hidden" value={ascent.id}/><button className="min-h-12 rounded-xl border border-red-700 px-5 font-bold text-red-700">Remove from logbook</button></form></div></details> : <p className="mt-4 text-xs text-[var(--muted)]">The 30-day editing window has closed.</p>}</article>; })}{media.length ? null : <p className="rounded-2xl border bg-white p-8 text-center text-[var(--muted)]">No ascents match these filters.</p>}</div>
  </div>;
}
