import { calculateStatistics } from "@/features/statistics/metrics";
import { requireActiveGymContext } from "@/lib/server/gym-context";
import { createServerComponentSupabaseClient } from "@/lib/supabase/server";

function Metric({ label, value, definition }: { label: string; value: string | number; definition: string }) { return <article className="rounded-[var(--radius-lg)] border bg-[var(--surface)] p-5"><p className="text-3xl font-black tabular-nums">{value}</p><h2 className="mt-2 font-black">{label}</h2><p className="mt-1 text-xs leading-5 text-[var(--muted)]">{definition}</p></article>; }

export default async function StatisticsPage({ params }: { params: Promise<{ gymSlug: string }> }) {
  const { gymSlug } = await params; const { gym } = await requireActiveGymContext({ gymSlug }); const supabase = await createServerComponentSupabaseClient(); const { data: { user } } = await supabase.auth.getUser();
  const [{ data: ascents }, { data: sessions }, { data: achievements }] = await Promise.all([
    supabase.from("ascent_logs").select("session_date,ascent_type,attempts,route_grade_snapshot,route_grade_system_snapshot").eq("gym_id", gym.id).eq("profile_id", user?.id ?? "").is("deleted_at", null),
    supabase.from("climbing_sessions").select("id,session_date").eq("gym_id", gym.id).eq("profile_id", user?.id ?? ""),
    supabase.from("member_achievements").select("id,title,description,context,awarded_at").eq("gym_id", gym.id).eq("profile_id", user?.id ?? "").order("awarded_at", { ascending: false }),
  ]);
  const metrics = calculateStatistics((ascents ?? []).map((item) => ({ sessionDate: item.session_date, outcome: item.ascent_type, attempts: item.attempts, grade: item.route_grade_snapshot, gradeSystem: item.route_grade_system_snapshot })), (sessions ?? []).map((item) => ({ id: item.id, sessionDate: item.session_date })));
  const maxGrade = Math.max(1, ...metrics.gradeDistribution.map(({ count }) => count)); const maxMonth = Math.max(1, ...metrics.monthlyProgress.map(({ count }) => count));
  return <div className="mx-auto max-w-[var(--content)]" id="statistics"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="app-eyebrow text-[var(--muted)]">Personal analytics</p><h1 className="mt-2 text-4xl font-extrabold tracking-[-.035em]">Progress at {gym.name}</h1><p className="mt-2 text-sm text-[var(--muted)]">Private ascents are included for you. Sparse data is shown as unavailable, never estimated.</p></div><p className="text-sm font-bold">Definitions are shown on each card.</p></div>
    <section aria-label="Climbing statistics" className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric definition="Distinct session records, all dates." label="Sessions" value={metrics.sessions}/><Metric definition="Flash, onsight, redpoint and repeat entries, all dates." label="Climbs" value={metrics.climbs}/><Metric definition="Sum across all entries, including projects." label="Attempts" value={metrics.attempts}/><Metric definition="Send entries divided by all entries." label="Success rate" value={metrics.successRate === null ? "Not available" : `${Math.round(metrics.successRate * 100)}%`}/><Metric definition="Entries recorded specifically as flash." label="Flashes" value={metrics.flashes}/><Metric definition="Highest recognised Font-grade send." label="Best send" value={metrics.bestSend ?? "Not available"}/><Metric definition="Longest run of Monday-to-Sunday weeks with a session." label="Weekly streak" value={`${metrics.longestWeeklyStreak} week${metrics.longestWeeklyStreak === 1 ? "" : "s"}`}/></section>
    <div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="rounded-[var(--radius-lg)] border bg-[var(--surface)] p-5"><h2 className="text-xl font-black">Sends by grade</h2><div aria-hidden="true" className="mt-5 space-y-3">{metrics.gradeDistribution.map(({ grade, count }) => <div key={grade}><div className="flex justify-between text-sm"><span>{grade}</span><strong>{count}</strong></div><div className="mt-1 h-3 rounded-full bg-[var(--surface-subtle)]"><div className="h-3 rounded-full bg-[var(--primary)]" style={{ width: `${count / maxGrade * 100}%` }}/></div></div>)}</div><table className="mt-5 w-full text-left text-sm"><caption className="sr-only">Accessible grade distribution data</caption><thead><tr><th className="py-2">Grade</th><th className="py-2">Successful climbs</th></tr></thead><tbody>{metrics.gradeDistribution.map(({ grade, count }) => <tr className="border-t" key={grade}><td className="py-2">{grade}</td><td className="py-2">{count}</td></tr>)}</tbody></table>{metrics.gradeDistribution.length ? null : <p className="mt-4 text-sm text-[var(--muted)]">No successful climbs have been logged.</p>}</section>
      <section className="rounded-[var(--radius-lg)] border bg-[var(--surface)] p-5"><h2 className="text-xl font-black">Successful climbs by month</h2><div aria-hidden="true" className="mt-5 flex min-h-44 items-end gap-2">{metrics.monthlyProgress.map(({ month, count }) => <div className="flex min-w-0 flex-1 flex-col items-center" key={month}><strong className="text-xs">{count}</strong><div className="mt-1 w-full rounded-t bg-[var(--accent)]" style={{ height: `${Math.max(8, count / maxMonth * 140)}px` }}/><span className="mt-2 text-[10px]">{month}</span></div>)}</div><table className="mt-5 w-full text-left text-sm"><caption className="sr-only">Accessible monthly progress data</caption><thead><tr><th className="py-2">Gym-local month</th><th className="py-2">Successful climbs</th></tr></thead><tbody>{metrics.monthlyProgress.map(({ month, count }) => <tr className="border-t" key={month}><td className="py-2">{month}</td><td className="py-2">{count}</td></tr>)}</tbody></table>{metrics.monthlyProgress.length ? null : <p className="mt-4 text-sm text-[var(--muted)]">Monthly progress will appear after a successful climb.</p>}</section></div>
    <section className="mt-8 rounded-[var(--radius-lg)] border bg-[var(--surface)] p-5"><h2 className="text-xl font-black">Achievements</h2><p className="mt-1 text-sm text-[var(--muted)]">Awards are processed idempotently whenever you save an ascent.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{(achievements ?? []).map((item) => <article className="rounded-[var(--radius-md)] bg-amber-50 p-4" key={item.id}><span aria-hidden="true" className="text-2xl">◆</span><h3 className="mt-2 font-black">{item.title}</h3><p className="mt-1 text-sm text-[var(--muted)]">{item.description}</p><p className="mt-2 text-xs">Awarded {new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(new Date(item.awarded_at))}</p></article>)}</div>{achievements?.length ? null : <p className="mt-5 text-sm text-[var(--muted)]">Log your first climb to begin earning achievements.</p>}</section>
  </div>;
}
