import { notFound } from "next/navigation";
import { triageRouteFeedbackAction } from "@/features/routes/feedback-actions";
import { requireActiveGymContext } from "@/lib/server/gym-context";
import { createServerComponentSupabaseClient } from "@/lib/supabase/server";

const labels: Record<string, string> = { spinning_hold: "Spinning hold", dirty_hold: "Dirty hold", other_issue: "Other issue" };

export default async function RouteFeedbackPage({ params }: { params: Promise<{ gymSlug: string }> }) {
  const { gymSlug } = await params; const { gym } = await requireActiveGymContext({ gymSlug, allowedRoles: ["owner","staff","route_setter"] }); const supabase = await createServerComponentSupabaseClient();
  if (gym.role === "staff") { const { data: membership } = await supabase.from("gym_memberships").select("staff_role_id").eq("id", gym.membershipId).single(); const { data: role } = membership?.staff_role_id ? await supabase.from("staff_roles").select("capabilities").eq("id", membership.staff_role_id).single() : { data: null }; if (!role?.capabilities.includes("route_feedback.read")) notFound(); }
  const { data: issues } = await supabase.from("route_feedback").select("id,feedback_kind,comment,issue_status,created_at,profile_id,routes(name,colour,grade,walls(name))").eq("gym_id", gym.id).in("feedback_kind", ["spinning_hold","dirty_hold","other_issue"]).is("archived_at", null).order("created_at", { ascending: false });
  const profileIds = [...new Set((issues ?? []).map(({ profile_id }) => profile_id))]; const { data: profiles } = profileIds.length ? await supabase.from("profiles").select("id,display_name").in("id", profileIds) : { data: [] }; const names = new Map((profiles ?? []).map((profile) => [profile.id, profile.display_name]));
  return <div className="mx-auto max-w-5xl"><p className="app-eyebrow text-[var(--muted)]">Route operations</p><h1 className="mt-3 text-4xl font-extrabold tracking-[-.035em]">Feedback triage</h1><p className="mt-3 text-[var(--muted)]">Reporter identities appear only in this permission-protected staff queue.</p><div className="mt-8 space-y-4">{issues?.map((issue) => <article className="rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface)] p-5" key={issue.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase text-[var(--muted)]">{labels[issue.feedback_kind] ?? issue.feedback_kind} · {issue.routes?.walls?.name}</p><h2 className="mt-1 text-xl font-black">{issue.routes?.name || `${issue.routes?.colour} ${issue.routes?.grade}`}</h2><p className="mt-2 text-sm text-[var(--muted)]">Reported by {names.get(issue.profile_id) ?? "Member"} · {new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(issue.created_at))}</p></div><span className="rounded-full bg-[var(--surface-subtle)] px-3 py-1 text-xs font-bold">{issue.issue_status}</span></div>{issue.comment ? <p className="mt-4 rounded-[var(--radius-md)] bg-[var(--surface-subtle)] p-4 text-sm">{issue.comment}</p> : null}<form action={triageRouteFeedbackAction} className="mt-4 flex flex-wrap gap-2"><input name="gymSlug" type="hidden" value={gym.slug} /><input name="feedbackId" type="hidden" value={issue.id} />{["open","reviewing","resolved","dismissed"].map((status) => <button className={`min-h-11 rounded-full border px-4 text-sm font-bold ${issue.issue_status === status ? "bg-[var(--primary)] text-white" : ""}`} disabled={issue.issue_status === status} key={status} name="status" value={status}>{status}</button>)}</form></article>)}{issues?.length ? null : <p className="rounded-[var(--radius-lg)] bg-[var(--surface)] p-5 text-sm text-[var(--muted)]">No route issues have been reported.</p>}</div></div>;
}
