import { notFound } from "next/navigation";
import { ManualMemberCheckIn, MemberTokenVerifier } from "@/components/member-check-in-panel";
import { requireActiveGymContext } from "@/lib/server/gym-context";
import { createServerComponentSupabaseClient } from "@/lib/supabase/server";

export default async function StaffCheckInPage({ params, searchParams }: { params: Promise<{ gymSlug: string }>; searchParams: Promise<{ member?: string | string[] }> }) {
  const [{ gymSlug }, search] = await Promise.all([params, searchParams]); const { gym } = await requireActiveGymContext({ gymSlug, allowedRoles: ["owner", "staff"] }); const supabase = await createServerComponentSupabaseClient();
  if (gym.role === "staff") { const { data: membership } = await supabase.from("gym_memberships").select("staff_role_id").eq("id", gym.membershipId).single(); const { data: role } = membership?.staff_role_id ? await supabase.from("staff_roles").select("capabilities").eq("id", membership.staff_role_id).single() : { data: null }; if (!(role?.capabilities.includes("guests.check_in") || role?.capabilities.includes("passes.manage"))) notFound(); }
  const raw = Array.isArray(search.member) ? search.member[0] : search.member; const query = (raw ?? "").trim().slice(0, 80);
  const { data: profiles } = query ? await supabase.from("profiles").select("id,display_name").ilike("display_name", `%${query.replace(/[%_]/g, "")}%`).limit(20) : { data: [] };
  const profileIds = (profiles ?? []).map(({ id }) => id); const { data: memberships } = profileIds.length ? await supabase.from("gym_memberships").select("id,profile_id").eq("gym_id", gym.id).eq("status", "active").in("profile_id", profileIds) : { data: [] }; const names = new Map((profiles ?? []).map((profile) => [profile.id, profile.display_name])); const members = (memberships ?? []).map((membership) => ({ membershipId: membership.id, displayName: names.get(membership.profile_id) ?? "Member" }));
  const { data: recent } = await supabase.from("check_ins").select("id,profile_id,guest_invite_id,source,checked_in_at,profiles!check_ins_profile_id_fkey(display_name),guest_invites(guest_name)").eq("gym_id", gym.id).order("checked_in_at", { ascending: false }).limit(20);
  return <div className="mx-auto max-w-5xl"><p className="app-eyebrow text-[var(--muted)]">Front desk</p><h1 className="mt-3 text-4xl font-extrabold tracking-[-.035em]">Member check-in</h1><div className="mt-8 grid gap-6 lg:grid-cols-2"><MemberTokenVerifier gymSlug={gym.slug} /><div><form className="mb-4 flex gap-2"><input className="min-h-11 flex-1 rounded-full border px-4" defaultValue={query} maxLength={80} name="member" placeholder="Member display name" /><button className="rounded-[var(--radius-md)] bg-[var(--primary)] px-5 text-sm font-bold text-white">Find member</button></form><ManualMemberCheckIn gymSlug={gym.slug} members={members} /></div></div><section className="mt-8 rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="text-xl font-black">Recent check-ins</h2><ul className="mt-3 divide-y">{recent?.map((item) => <li className="flex flex-wrap justify-between gap-2 py-3 text-sm" key={item.id}><span className="font-bold">{item.profiles?.display_name ?? item.guest_invites?.guest_name ?? "Visitor"}</span><span>{item.source.replace("_", " ")} · {new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.checked_in_at))}</span></li>)}{recent?.length ? null : <li className="py-3 text-sm text-[var(--muted)]">No check-ins recorded.</li>}</ul></section></div>;
}
