import Link from "next/link";
import { RouteExplorer } from "@/components/route-explorer";
import { explorerSearch, filterExplorerRoutes, parseExplorerFilters } from "@/features/routes/explorer";
import { routeOverlaySchema } from "@/features/routes/validation";
import { requireActiveGymContext } from "@/lib/server/gym-context";
import { createServerComponentSupabaseClient } from "@/lib/supabase/server";

type Search = Record<string, string | string[] | undefined>;
const unique = (values: (string | null)[]) => [...new Set(values.filter((value): value is string => Boolean(value)))].sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

export default async function RoutesPage({ params, searchParams }: { params: Promise<{ gymSlug: string }>; searchParams: Promise<Search> }) {
  const [{ gymSlug }, rawFilters] = await Promise.all([params, searchParams]);
  const { gym } = await requireActiveGymContext({ gymSlug }); const supabase = await createServerComponentSupabaseClient();
  const [{ data: walls }, { data: records }] = await Promise.all([
    supabase.from("walls").select("id,name,sort_order,wall_images(id,storage_path,alt_text,width,height,is_current,archived_at)").eq("gym_id", gym.id).eq("is_active", true).is("archived_at", null).order("sort_order"),
    supabase.from("routes").select("id,wall_id,wall_image_id,name,colour,grade_system,grade,route_type,setter_id,set_on,retire_on,description,overlay,walls(name),route_tags(tag)").eq("gym_id", gym.id).eq("status", "published").order("set_on", { ascending: false }),
  ]);
  const parsed = parseExplorerFilters(rawFilters); const effectiveFilters = { ...parsed, wall: parsed.wall || walls?.[0]?.id || "" };
  const setterIds = unique((records ?? []).map(({ setter_id }) => setter_id));
  const { data: setterProfiles } = setterIds.length ? await supabase.from("profiles").select("id,display_name").in("id", setterIds) : { data: [] };
  const setterNames = new Map((setterProfiles ?? []).map((profile) => [profile.id, profile.display_name]));
  const normalized = (records ?? []).map((route) => ({ ...route, tags: route.route_tags.map(({ tag }) => tag) }));
  const filtered = filterExplorerRoutes(normalized, effectiveFilters);
  const selectedWall = walls?.find((wall) => wall.id === effectiveFilters.wall) ?? null;
  const currentImage = selectedWall?.wall_images.find((item) => item.is_current && !item.archived_at) ?? null;
  const signedUrl = currentImage ? (await supabase.storage.from("wall-images").createSignedUrl(currentImage.storage_path, 60 * 60)).data?.signedUrl ?? null : null;
  const image = currentImage && signedUrl ? { url: signedUrl, alt: currentImage.alt_text, width: currentImage.width, height: currentImage.height } : null;
  const explorerRoutes = filtered.map((route) => ({ id: route.id, name: route.name, wallName: route.walls?.name ?? "Unknown wall", colour: route.colour, grade: route.grade, gradeSystem: route.grade_system, discipline: route.route_type, setterName: route.setter_id ? setterNames.get(route.setter_id) ?? null : null, setOn: route.set_on, retireOn: route.retire_on, description: route.description, tags: route.tags, overlay: routeOverlaySchema.safeParse(route.overlay).data ?? null }));
  const base = `/g/${gym.slug}/app/routes`; const activeSearch = explorerSearch(effectiveFilters);
  const grades = unique(normalized.map(({ grade }) => grade)); const disciplines = unique(normalized.map(({ route_type }) => route_type)); const styles = unique(normalized.flatMap(({ tags }) => tags)); const colours = unique(normalized.map(({ colour }) => colour));

  return <div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[0.2em] text-[var(--muted)]">Routes</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-4xl font-black">Route Explorer</h1><p className="mt-2 text-[var(--muted)]">Explore the current wall, or switch to a keyboard-friendly list.</p></div><div aria-label="Explorer view" className="flex rounded-full border bg-white p-1"><Link aria-current={effectiveFilters.view === "map" ? "page" : undefined} className={`rounded-full px-4 py-2 text-sm font-bold ${effectiveFilters.view === "map" ? "bg-black text-white" : ""}`} href={`${base}${explorerSearch(effectiveFilters, { view: "map" })}`}>Map</Link><Link aria-current={effectiveFilters.view === "list" ? "page" : undefined} className={`rounded-full px-4 py-2 text-sm font-bold ${effectiveFilters.view === "list" ? "bg-black text-white" : ""}`} href={`${base}${explorerSearch(effectiveFilters, { view: "list" })}`}>List</Link></div></div>
    <form action={base} className="my-8 grid gap-3 rounded-2xl border border-[var(--border)] bg-white p-5 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7" method="get"><input name="view" type="hidden" value={effectiveFilters.view} /><label className="text-sm font-bold">Wall / sector<select className="mt-1 w-full rounded-lg border p-3 font-normal" defaultValue={effectiveFilters.wall} name="wall">{walls?.map((wall) => <option key={wall.id} value={wall.id}>{wall.name}</option>)}</select></label><label className="text-sm font-bold">Grade<select className="mt-1 w-full rounded-lg border p-3 font-normal" defaultValue={effectiveFilters.grade} name="grade"><option value="">All grades</option>{grades.map((grade) => <option key={grade}>{grade}</option>)}</select></label><label className="text-sm font-bold">Discipline<select className="mt-1 w-full rounded-lg border p-3 font-normal" defaultValue={effectiveFilters.discipline} name="discipline"><option value="">All disciplines</option>{disciplines.map((discipline) => <option key={discipline} value={discipline}>{discipline.replace("_", " ")}</option>)}</select></label><label className="text-sm font-bold">Style<select className="mt-1 w-full rounded-lg border p-3 font-normal" defaultValue={effectiveFilters.style} name="style"><option value="">All styles</option>{styles.map((style) => <option key={style}>{style}</option>)}</select></label><label className="text-sm font-bold">Colour<select className="mt-1 w-full rounded-lg border p-3 font-normal" defaultValue={effectiveFilters.colour} name="colour"><option value="">All colours</option>{colours.map((colour) => <option key={colour}>{colour}</option>)}</select></label><label className="text-sm font-bold">Setter<select className="mt-1 w-full rounded-lg border p-3 font-normal" defaultValue={effectiveFilters.setter} name="setter"><option value="">All setters</option>{setterProfiles?.map((setter) => <option key={setter.id} value={setter.id}>{setter.display_name}</option>)}</select></label><label className="text-sm font-bold">Set since<input className="mt-1 w-full rounded-lg border p-3 font-normal" defaultValue={effectiveFilters.setSince} name="setSince" type="date" /></label><div className="flex gap-2 sm:col-span-2 lg:col-span-4 xl:col-span-7"><button className="min-h-11 rounded-full bg-black px-5 text-sm font-bold text-white">Apply filters</button><Link className="inline-flex min-h-11 items-center rounded-full border px-5 text-sm font-bold" href={base}>Clear</Link></div></form>
    <RouteExplorer detailBase={base} image={image} returnSearch={activeSearch} routes={explorerRoutes} view={effectiveFilters.view} />
  </div>;
}
