import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { RouteFeedbackControls } from "@/components/route-feedback-controls";
import { routeOverlaySchema } from "@/features/routes/validation";
import { requireActiveGymContext } from "@/lib/server/gym-context";
import { createServerComponentSupabaseClient } from "@/lib/supabase/server";

type Metrics = { favourites: number; ascents: number; loved: number; grade_soft: number; grade_right: number; grade_hard: number };
const emptyMetrics: Metrics = { favourites: 0, ascents: 0, loved: 0, grade_soft: 0, grade_right: 0, grade_hard: 0 };
function metricsFrom(value: unknown): Metrics { if (!value || typeof value !== "object" || Array.isArray(value)) return emptyMetrics; const row = value as Record<string, unknown>; return Object.fromEntries(Object.keys(emptyMetrics).map((key) => [key, typeof row[key] === "number" ? row[key] : 0])) as Metrics; }
function date(value: string | null) { return value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "long" }).format(new Date(`${value}T12:00:00Z`)) : "Not recorded"; }

export default async function RoutePage({ params, searchParams }: { params: Promise<{ gymSlug: string; routeId: string }>; searchParams: Promise<{ from?: string | string[] }> }) {
  const [{ gymSlug, routeId }, search] = await Promise.all([params, searchParams]); const { gym } = await requireActiveGymContext({ gymSlug });
  const supabase = await createServerComponentSupabaseClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) notFound();
  const { data: route } = await supabase.from("routes").select("id,wall_id,wall_image_id,name,colour,grade_system,grade,route_type,setter_id,set_on,retire_on,description,overlay,walls(name),route_tags(tag),route_media(id,storage_path,alt_text,media_type,processing_status,archived_at)").eq("id", routeId).eq("gym_id", gym.id).eq("status", "published").single();
  if (!route) notFound();
  const [{ data: setter }, { data: favourite }, { data: ownFeedback }, metricsResult, { data: related }] = await Promise.all([
    route.setter_id ? supabase.from("profiles").select("display_name").eq("id", route.setter_id).single() : Promise.resolve({ data: null }),
    supabase.from("favourites").select("id").eq("gym_id", gym.id).eq("route_id", route.id).eq("profile_id", user.id).maybeSingle(),
    supabase.from("route_feedback").select("feedback_kind").eq("gym_id", gym.id).eq("route_id", route.id).eq("profile_id", user.id).is("archived_at", null),
    supabase.rpc("get_route_public_metrics", { target_gym_id: gym.id, target_route_id: route.id }),
    supabase.from("routes").select("id,name,colour,grade,route_type,walls(name)").eq("gym_id", gym.id).eq("status", "published").eq("wall_id", route.wall_id).neq("id", route.id).limit(4),
  ]);
  const overlay = routeOverlaySchema.safeParse(route.overlay).data ?? null;
  const { data: wallImage } = route.wall_image_id ? await supabase.from("wall_images").select("storage_path,alt_text,width,height").eq("id", route.wall_image_id).eq("gym_id", gym.id).single() : { data: null };
  const wallUrl = wallImage ? (await supabase.storage.from("wall-images").createSignedUrl(wallImage.storage_path, 60 * 60)).data?.signedUrl ?? null : null;
  const readyMedia = route.route_media.filter((media) => media.processing_status === "ready" && !media.archived_at && media.media_type === "image");
  const mediaUrls = await Promise.all(readyMedia.map(async (media) => ({ ...media, url: (await supabase.storage.from("route-media").createSignedUrl(media.storage_path, 60 * 60)).data?.signedUrl ?? null })));
  const candidate = Array.isArray(search.from) ? search.from[0] : search.from; const base = `/g/${gym.slug}/app/routes`; const backHref = candidate?.startsWith(`${base}?`) ? candidate : base; const metrics = metricsFrom(metricsResult.data);
  const gradeVotes = metrics.grade_soft + metrics.grade_right + metrics.grade_hard;
  return <div className="mx-auto max-w-5xl"><Link className="inline-flex min-h-11 items-center font-bold underline" href={backHref}>← Back to filtered routes</Link><div className="mt-5 grid gap-6 lg:grid-cols-[minmax(0,3fr)_minmax(18rem,2fr)]"><main className="space-y-6"><article className="rounded-2xl border border-[var(--border)] bg-white p-6"><p className="text-sm font-bold uppercase tracking-wide text-[var(--muted)]">{route.walls?.name} · {route.route_type.replace("_", " ")}</p><h1 className="mt-3 text-4xl font-black">{route.name || `${route.colour} ${route.grade}`}</h1><p className="mt-4 text-xl font-bold">{route.grade_system} {route.grade} · {route.colour}</p><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-3"><div><dt className="font-bold text-[var(--muted)]">Setter</dt><dd>{setter?.display_name ?? "Not listed"}</dd></div><div><dt className="font-bold text-[var(--muted)]">Set date</dt><dd>{date(route.set_on)}</dd></div><div><dt className="font-bold text-[var(--muted)]">Planned removal</dt><dd>{date(route.retire_on)}</dd></div></dl>{route.description ? <p className="mt-5 text-[var(--muted)]">{route.description}</p> : null}<div className="mt-5 flex flex-wrap gap-2">{route.route_tags.map(({ tag }) => <span className="rounded-full bg-stone-100 px-3 py-1 text-sm font-bold" key={tag}>{tag}</span>)}</div></article>
      {wallImage && wallUrl ? <figure className="rounded-2xl border border-[var(--border)] bg-white p-3"><div className="relative overflow-hidden rounded-xl"><Image alt={wallImage.alt_text} className="h-auto w-full" height={wallImage.height} priority src={wallUrl} unoptimized width={wallImage.width} />{overlay?.kind === "point" ? <span aria-hidden="true" className="absolute h-6 w-6 -translate-x-1/2 -translate-y-1/2 rounded-full border-4 border-white bg-red-600 shadow" style={{ left: `${overlay.x * 100}%`, top: `${overlay.y * 100}%` }} /> : overlay?.kind === "polygon" ? <svg aria-hidden="true" className="absolute inset-0 h-full w-full" viewBox="0 0 100 100"><polygon fill="rgba(220,38,38,.25)" points={overlay.points.map((point) => `${point.x * 100},${point.y * 100}`).join(" ")} stroke="white" strokeWidth=".8" vectorEffect="non-scaling-stroke" /></svg> : null}</div><figcaption className="px-2 pt-3 text-sm text-[var(--muted)]">Route location on {route.walls?.name}.</figcaption></figure> : null}
      {mediaUrls.some(({ url }) => url) ? <section><h2 className="text-xl font-black">Route media</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{mediaUrls.map((media) => media.url ? <Image alt={media.alt_text || `Media for ${route.name || route.grade}`} className="h-auto w-full rounded-xl" height={800} key={media.id} src={media.url} unoptimized width={1200} /> : null)}</div></section> : null}
      <RouteFeedbackControls favourite={Boolean(favourite)} gymSlug={gym.slug} routeId={route.id} submitted={(ownFeedback ?? []).map(({ feedback_kind }) => feedback_kind)} /></main>
      <aside className="space-y-6"><section className="rounded-2xl border border-[var(--border)] bg-white p-5"><h2 className="text-xl font-black">Community activity</h2><dl className="mt-4 grid grid-cols-3 gap-2 text-center"><div className="rounded-xl bg-stone-100 p-3"><dt className="text-xs text-[var(--muted)]">Favourites</dt><dd className="text-2xl font-black">{metrics.favourites}</dd></div><div className="rounded-xl bg-stone-100 p-3"><dt className="text-xs text-[var(--muted)]">Ascents</dt><dd className="text-2xl font-black">{metrics.ascents}</dd></div><div className="rounded-xl bg-stone-100 p-3"><dt className="text-xs text-[var(--muted)]">Loved</dt><dd className="text-2xl font-black">{metrics.loved}</dd></div></dl>{gradeVotes ? <p className="mt-4 text-sm text-[var(--muted)]">Grade votes: {metrics.grade_soft} soft · {metrics.grade_right} right · {metrics.grade_hard} hard</p> : <p className="mt-4 text-sm text-[var(--muted)]">No grade votes yet.</p>}</section><section className="rounded-2xl border border-[var(--border)] bg-white p-5"><h2 className="text-xl font-black">Nearby routes</h2><ul className="mt-3 space-y-2">{related?.map((item) => <li key={item.id}><Link className="block rounded-lg p-3 hover:bg-stone-100 focus:outline-none focus:ring-2 focus:ring-black" href={`${base}/${item.id}?from=${encodeURIComponent(backHref)}`}><span className="block font-bold">{item.name || `${item.colour} ${item.grade}`}</span><span className="text-xs text-[var(--muted)]">{item.grade} · {item.route_type.replace("_", " ")}</span></Link></li>)}{related?.length ? null : <li className="text-sm text-[var(--muted)]">No nearby routes are published.</li>}</ul></section></aside></div></div>;
}
