"use client";

import { Select } from "@/components/ui/form-controls";
import { useActionState } from "react";
import { saveAscentAction } from "@/features/ascents/actions";
import { initialAscentState } from "@/features/ascents/state";

type Value = { id: string; session_id: string | null; session_date: string; ascent_type: string; attempts: number; notes: string | null; visibility: string };
export function AscentForm({ gymSlug, routeId, sessions, value }: { gymSlug: string; routeId: string; sessions: { id: string; session_date: string }[]; value?: Value }) {
  const [state, action, pending] = useActionState(saveAscentAction, initialAscentState); const today = new Date().toISOString().slice(0, 10);
  return <form action={action} className="grid gap-3 sm:grid-cols-2"><input name="gymSlug" type="hidden" value={gymSlug}/><input name="routeId" type="hidden" value={routeId}/><input name="ascentId" type="hidden" value={value?.id ?? ""}/><label className="text-sm font-bold">Outcome<Select className="mt-1 w-full rounded-[var(--radius-sm)] border p-3 font-normal" defaultValue={value?.ascent_type ?? "redpoint"} name="outcome"><option value="flash">Flash</option><option value="onsight">Onsight</option><option value="redpoint">Redpoint</option><option value="repeat">Repeat</option><option value="attempted">Attempted</option><option value="project">Project</option></Select></label><label className="text-sm font-bold">Attempts<input className="mt-1 w-full rounded-[var(--radius-sm)] border p-3 font-normal" defaultValue={value?.attempts ?? 1} max={999} min={1} name="attempts" required type="number"/></label><label className="text-sm font-bold">Session date<input className="mt-1 w-full rounded-[var(--radius-sm)] border p-3 font-normal" defaultValue={value?.session_date ?? today} max={today} name="sessionDate" required type="date"/></label><label className="text-sm font-bold">Session<Select className="mt-1 w-full rounded-[var(--radius-sm)] border p-3 font-normal" defaultValue={value?.session_id ?? ""} name="sessionId"><option value="">Start a new session</option>{sessions.map((session) => <option key={session.id} value={session.id}>{session.session_date}</option>)}</Select></label><label className="text-sm font-bold">Privacy<Select className="mt-1 w-full rounded-[var(--radius-sm)] border p-3 font-normal" defaultValue={value?.visibility ?? "private"} name="visibility"><option value="private">Only me</option><option value="gym">Members of this gym</option><option value="public">Public profile (when available)</option></Select></label><label className="text-sm font-bold">Photo or video<input accept="image/png,image/jpeg,image/webp,video/mp4" className="mt-2 block w-full font-normal" name="media" type="file"/></label><label className="text-sm font-bold sm:col-span-2">Notes<textarea className="mt-1 min-h-20 w-full rounded-[var(--radius-sm)] border p-3 font-normal" defaultValue={value?.notes ?? ""} maxLength={2000} name="notes"/></label><button className="min-h-12 rounded-[var(--radius-md)] bg-[var(--primary)] px-5 font-bold text-white sm:col-span-2" disabled={pending}>{pending ? "Saving…" : value ? "Save changes" : "Log ascent"}</button>{state.message ? <p aria-live="polite" className={`text-sm sm:col-span-2 ${state.status === "error" ? "text-red-700" : "text-emerald-700"}`}>{state.message}</p> : null}</form>;
}
