"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";

type PointOverlay = { kind: "point"; x: number; y: number };
type PolygonOverlay = { kind: "polygon"; points: { x: number; y: number }[] };
type Route = { id: string; name: string | null; wallName: string; colour: string; grade: string; gradeSystem: string; discipline: string; setterName: string | null; setOn: string | null; retireOn: string | null; description: string | null; tags: string[]; overlay: PointOverlay | PolygonOverlay | null };

function label(route: Route) { return route.name || `${route.colour} ${route.grade}`; }
function polygonCentre(points: { x: number; y: number }[]) {
  const total = points.reduce((sum, point) => ({ x: sum.x + point.x, y: sum.y + point.y }), { x: 0, y: 0 });
  return { x: total.x / points.length, y: total.y / points.length };
}

export function RouteExplorer({ routes, view, image, detailBase, returnSearch }: { routes: Route[]; view: "map" | "list"; image: { url: string; alt: string; width: number; height: number } | null; detailBase: string; returnSearch: string }) {
  const [selectedId, setSelectedId] = useState(routes[0]?.id ?? null); const [zoom, setZoom] = useState(1);
  const selected = routes.find((route) => route.id === selectedId) ?? null;
  const detailHref = (id: string) => `${detailBase}/${id}?from=${encodeURIComponent(`${detailBase}${returnSearch}`)}#log-ascent`;
  if (!routes.length) return <p className="rounded-[var(--radius-lg)] bg-[var(--surface)] p-6 text-sm text-[var(--muted)]">No published routes match these filters.</p>;
  return <div className="grid gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(18rem,1fr)]">
    <section aria-label={view === "map" ? "Route map" : "Filtered routes"}>
      {view === "map" ? image ? <div className="rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface)] p-3"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><p aria-live="polite" className="text-sm font-bold">Zoom {Math.round(zoom * 100)}%</p><div className="flex gap-2"><button aria-label="Zoom out" className="min-h-11 min-w-11 rounded-[var(--radius-md)] border font-black" disabled={zoom <= 1} onClick={() => setZoom((current) => Math.max(1, current - 0.25))}>−</button><button aria-label="Reset zoom" className="min-h-11 rounded-[var(--radius-md)] border px-4 text-sm font-bold" onClick={() => setZoom(1)}>Reset</button><button aria-label="Zoom in" className="min-h-11 min-w-11 rounded-[var(--radius-md)] border font-black" disabled={zoom >= 3} onClick={() => setZoom((current) => Math.min(3, current + 0.25))}>+</button></div></div><p className="mb-3 text-xs text-[var(--muted)]">Zoom, then scroll horizontally or vertically to pan. Every map control is also available in the filtered routes list.</p><div aria-label="Scrollable wall image and route controls" className="max-h-[70vh] overflow-auto rounded-[var(--radius-md)] bg-[var(--surface-subtle)]" role="region" tabIndex={0}><div className="relative" style={{ width: `${zoom * 100}%` }}><Image alt={image.alt} className="h-auto w-full" height={image.height} priority src={image.url} unoptimized width={image.width} />{routes.map((route) => {
        if (route.overlay?.kind === "point") return <button aria-label={`Select ${label(route)}, ${route.grade}, ${route.colour}`} className={`absolute min-h-7 min-w-7 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white bg-red-600 shadow focus:outline-none focus:ring-4 focus:ring-[var(--focus-ring)] ${selectedId === route.id ? "ring-4 ring-[var(--focus-ring)]" : ""}`} key={route.id} onClick={() => setSelectedId(route.id)} style={{ left: `${route.overlay.x * 100}%`, top: `${route.overlay.y * 100}%` }} type="button"><span className="sr-only">{label(route)}</span></button>;
        if (route.overlay?.kind !== "polygon") return null;
        const centre = polygonCentre(route.overlay.points);
        return <div key={route.id}><svg aria-hidden="true" className="pointer-events-none absolute inset-0 h-full w-full overflow-visible" viewBox="0 0 100 100"><polygon fill="rgba(220,38,38,.24)" points={route.overlay.points.map((point) => `${point.x * 100},${point.y * 100}`).join(" ")} stroke={selectedId === route.id ? "black" : "white"} strokeWidth={selectedId === route.id ? 1.2 : 0.7} vectorEffect="non-scaling-stroke" /></svg><button aria-label={`Select ${label(route)}, ${route.grade}, ${route.colour}`} className="absolute min-h-7 min-w-7 -translate-x-1/2 -translate-y-1/2 rounded-[var(--radius-md)] border-2 border-white bg-red-600 shadow focus:ring-4 focus:ring-[var(--focus-ring)]" onClick={() => setSelectedId(route.id)} style={{ left: `${centre.x * 100}%`, top: `${centre.y * 100}%` }} type="button"><span className="sr-only">{label(route)}</span></button></div>;
      })}</div></div></div> : <p className="rounded-[var(--radius-lg)] bg-amber-50 p-6 text-sm">This wall does not have a current image. Use the accessible route list.</p> : <div className="grid gap-4 sm:grid-cols-2">{routes.map((route) => <article className="rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface)] p-5" key={route.id}><p className="text-xs font-bold uppercase text-[var(--muted)]">{route.wallName} · {route.discipline.replace("_", " ")}</p><h2 className="mt-2 text-xl font-black">{label(route)}</h2><p className="mt-2 text-sm">{route.gradeSystem} {route.grade} · {route.setterName ?? "Setter not listed"}</p><div className="mt-3 flex flex-wrap gap-2">{route.tags.map((tag) => <span className="rounded-full bg-[var(--surface-subtle)] px-2 py-1 text-xs font-bold" key={tag}>{tag}</span>)}</div><Link className="mt-4 inline-flex min-h-11 items-center font-bold underline" href={detailHref(route.id)}>View full route</Link></article>)}</div>}
    </section>
    <aside aria-label="Accessible route navigation" className="space-y-4"><div className="rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="font-black">Filtered routes ({routes.length})</h2><ul className="mt-3 max-h-80 space-y-1 overflow-auto">{routes.map((route) => <li key={route.id}><button aria-current={selectedId === route.id ? "true" : undefined} className={`w-full rounded-[var(--radius-sm)] px-3 py-3 text-left text-sm focus:outline-none focus:ring-2 focus:ring-[var(--focus-ring)] ${selectedId === route.id ? "bg-[var(--primary)] font-bold text-white" : "hover:bg-[var(--surface-subtle)]"}`} onClick={() => setSelectedId(route.id)} type="button"><span className="block font-bold">{label(route)}</span><span className="block text-xs opacity-75">{route.grade} · {route.wallName} · {route.colour}</span></button></li>)}</ul></div>{selected ? <article aria-live="polite" className="rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface)] p-5"><p className="text-xs font-bold uppercase text-[var(--muted)]">Selected route</p><h2 className="mt-2 text-2xl font-black">{label(selected)}</h2><p className="mt-2 text-sm">{selected.gradeSystem} {selected.grade} · {selected.discipline.replace("_", " ")}</p><p className="mt-1 text-sm">{selected.wallName} · {selected.setterName ?? "Setter not listed"}</p>{selected.description ? <p className="mt-3 text-sm text-[var(--muted)]">{selected.description}</p> : null}<Link className="mt-4 inline-flex min-h-11 items-center rounded-[var(--radius-md)] bg-[var(--primary)] px-4 text-sm font-bold text-white" href={detailHref(selected.id)}>View full route</Link></article> : null}</aside>
  </div>;
}
