"use client";

import { useActionState } from "react";
import { saveWaiverDraftAction } from "@/features/waivers/actions";
import { initialWaiverState } from "@/features/waivers/state";
import type { WaiverRequirements } from "@/features/waivers/validation";

export function WaiverEditor({ gymSlug, waiver, draft }: { gymSlug:string; waiver?:{id:string;name:string;description:string|null;is_required:boolean}; draft?:{title:string;content:string;requirements:WaiverRequirements} }) {
  const [state,action,pending]=useActionState(saveWaiverDraftAction,initialWaiverState);const requirements=draft?.requirements;
  return <form action={action} className="grid gap-4 md:grid-cols-2"><input name="gymSlug" type="hidden" value={gymSlug}/><input name="waiverId" type="hidden" value={waiver?.id??""}/><label className="text-sm font-bold">Template name<input className="mt-1 w-full rounded-[var(--radius-sm)] border p-3 font-normal" defaultValue={waiver?.name} maxLength={160} name="name" required/></label><label className="text-sm font-bold">Version title<input className="mt-1 w-full rounded-[var(--radius-sm)] border p-3 font-normal" defaultValue={draft?.title} maxLength={200} name="title" required/></label><label className="text-sm font-bold md:col-span-2">Internal description<input className="mt-1 w-full rounded-[var(--radius-sm)] border p-3 font-normal" defaultValue={waiver?.description??""} maxLength={1000} name="description"/></label><label className="text-sm font-bold md:col-span-2">Waiver text<textarea className="mt-1 min-h-72 w-full rounded-[var(--radius-sm)] border p-3 font-mono text-sm font-normal" defaultValue={draft?.content} maxLength={100000} name="content" required/></label><label className="flex items-center gap-2 text-sm font-bold"><input defaultChecked={waiver?.is_required??true} name="requiredForEntry" type="checkbox"/>Required for entry</label><label className="flex items-center gap-2 text-sm font-bold"><input defaultChecked={requirements?.collect_date_of_birth} name="collectDateOfBirth" type="checkbox"/>Collect date of birth</label><label className="flex items-center gap-2 text-sm font-bold"><input defaultChecked={requirements?.require_age_confirmation??true} name="requireAgeConfirmation" type="checkbox"/>Require age declaration</label><label className="text-sm font-bold">Minimum declared age<input className="mt-1 w-full rounded-[var(--radius-sm)] border p-3 font-normal" defaultValue={requirements?.minimum_age??18} max={120} min={1} name="minimumAge" type="number"/></label><label className="flex items-center gap-2 text-sm font-bold md:col-span-2"><input defaultChecked={requirements?.collect_emergency_contact} name="collectEmergencyContact" type="checkbox"/>Collect emergency contact</label><label className="text-sm font-bold md:col-span-2">Required consent statements (one per line)<textarea className="mt-1 min-h-28 w-full rounded-[var(--radius-sm)] border p-3 font-normal" defaultValue={requirements?.consent_items.join("\n")??"I have read and agree to this waiver"} maxLength={10000} name="consentItems" required/></label><button className="min-h-11 rounded-[var(--radius-md)] bg-[var(--primary)] px-5 font-bold text-white md:col-span-2" disabled={pending}>{pending?"Saving…":"Save draft"}</button>{state.message?<p className={`text-sm md:col-span-2 ${state.status==="error"?"text-red-700":"text-emerald-700"}`}>{state.message}</p>:null}</form>;
}
