"use server";
import{revalidatePath}from"next/cache";import{z}from"zod";import{hasValidImageSignature,routeImageSchema}from"@/features/routes/validation";import{requireActiveGymContext}from"@/lib/server/gym-context";import{createServerComponentSupabaseClient}from"@/lib/supabase/server";
const slug=z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),base=z.object({gymSlug:slug});async function context(gymSlug:string){return requireActiveGymContext({gymSlug});}function refresh(gymSlug:string){revalidatePath(`/g/${gymSlug}/app/community`);revalidatePath(`/g/${gymSlug}/app`);}
export async function acceptGuidelinesAction(formData:FormData){const parsed=base.parse(Object.fromEntries(formData.entries()));const{gym}=await context(parsed.gymSlug),supabase=await createServerComponentSupabaseClient();await supabase.rpc("accept_community_guidelines",{target_gym_id:gym.id});refresh(gym.slug);}
export async function createPostAction(formData:FormData){const parsed=base.extend({title:z.string().trim().max(200),body:z.string().trim().min(1).max(10000)}).parse(Object.fromEntries(formData.entries()));const{gym}=await context(parsed.gymSlug),supabase=await createServerComponentSupabaseClient();let imagePath:string|null=null;const image=formData.get("image");if(image instanceof File&&image.size){const valid=routeImageSchema.safeParse(image);if(!valid.success||!(await hasValidImageSignature(image)))throw new Error("Use a valid PNG, JPEG or WebP image up to 10 MB.");const extension=image.type==="image/png"?"png":image.type==="image/webp"?"webp":"jpg";imagePath=`${gym.id}/${crypto.randomUUID()}.${extension}`;const upload=await supabase.storage.from("community-images").upload(imagePath,image,{contentType:image.type});if(upload.error)throw new Error("Image upload failed.");}const{error}=await supabase.rpc("create_community_post",{target_gym_id:gym.id,post_title:parsed.title,post_body:parsed.body,post_image_path:imagePath});if(error){if(imagePath)await supabase.storage.from("community-images").remove([imagePath]);throw new Error(error.message);}refresh(gym.slug);}
export async function commentAction(formData:FormData){const parsed=base.extend({postId:z.uuid(),body:z.string().trim().min(1).max(5000)}).parse(Object.fromEntries(formData.entries()));const{gym}=await context(parsed.gymSlug),supabase=await createServerComponentSupabaseClient();await supabase.rpc("create_community_comment",{target_gym_id:gym.id,target_post_id:parsed.postId,comment_body:parsed.body});refresh(gym.slug);}
export async function reactionAction(formData:FormData){const parsed=base.extend({postId:z.uuid(),reaction:z.enum(["like","love","strong","celebrate","support"])}).parse(Object.fromEntries(formData.entries()));const{gym}=await context(parsed.gymSlug),supabase=await createServerComponentSupabaseClient();await supabase.rpc("toggle_community_reaction",{target_gym_id:gym.id,target_post_id:parsed.postId,reaction_name:parsed.reaction});refresh(gym.slug);}
export async function deleteContentAction(formData:FormData){const parsed=base.extend({targetId:z.uuid(),targetType:z.enum(["post","comment"])}).parse(Object.fromEntries(formData.entries()));const{gym}=await context(parsed.gymSlug),supabase=await createServerComponentSupabaseClient();await supabase.rpc("delete_community_content",{target_gym_id:gym.id,target_type:parsed.targetType,target_id:parsed.targetId});refresh(gym.slug);}
export async function reportContentAction(formData:FormData){const parsed=base.extend({targetId:z.uuid(),targetType:z.enum(["post","comment"]),reason:z.string().trim().min(3).max(1000)}).parse(Object.fromEntries(formData.entries()));const{gym}=await context(parsed.gymSlug),supabase=await createServerComponentSupabaseClient();await supabase.rpc("report_community_content",{target_gym_id:gym.id,target_type:parsed.targetType,target_id:parsed.targetId,report_reason:parsed.reason});refresh(gym.slug);}
export async function moderatePostAction(formData:FormData){const parsed=base.extend({postId:z.uuid(),status:z.enum(["visible","hidden","removed"]),reason:z.string().trim().min(3).max(1000)}).parse(Object.fromEntries(formData.entries()));const{gym}=await requireActiveGymContext({gymSlug:parsed.gymSlug,allowedRoles:["owner","staff"]}),supabase=await createServerComponentSupabaseClient();await supabase.rpc("moderate_community_post",{target_gym_id:gym.id,target_post_id:parsed.postId,target_status:parsed.status,lock_post:formData.get("lockPost")==="on",pin_post:formData.get("pinPost")==="on",reason:parsed.reason});refresh(gym.slug);}
