"use server";

import { createHash, randomBytes } from "node:crypto";
import { revalidatePath } from "next/cache";
import QRCode from "qrcode";
import { z } from "zod";
import { privilegedAccess } from "@/lib/supabase/admin";
import { requireActiveGymContext } from "@/lib/server/gym-context";
import { createServerComponentSupabaseClient } from "@/lib/supabase/server";
import { deferredGymPaymentProvider } from "./payment-provider";
import type { GuestRegistrationState,PassVerificationState } from "./state";

const slug=z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/);const registration=z.object({gymSlug:slug,guestName:z.string().trim().min(1).max(120),guestEmail:z.union([z.email().trim().toLowerCase().max(320),z.literal("")]),paymentChoice:z.enum(["pay_at_reception","integration_placeholder"])});
const hash=(value:string)=>createHash("sha256").update(value).digest("hex");
function rawToken(){return randomBytes(32).toString("base64url");}
function normalizeReference(value:unknown){const parsed=z.string().trim().min(32).max(128).parse(value);const raw=parsed.startsWith("CRUXPASS1.")?parsed.slice(10):parsed;return z.string().regex(/^[A-Za-z0-9_-]{32,100}$/).parse(raw);}
async function result(inviteToken:string,passToken:string,validUntil:string,paymentChoice:"pay_at_reception"|"integration_placeholder"):Promise<GuestRegistrationState>{const reference=`CRUXPASS1.${passToken}`;const payment=await deferredGymPaymentProvider.reserve(paymentChoice);return{status:"success",message:payment.state==="unpaid"?"Reserved—payment is due at reception.":"Reserved using the integration placeholder. No payment was charged.",waiverUrl:`/waiver/${inviteToken}`,passReference:reference,qrDataUrl:await QRCode.toDataURL(reference,{errorCorrectionLevel:"M",margin:2,width:320}),validUntil,paymentState:payment.state};}
function registrationFields(formData:FormData){return registration.safeParse(Object.fromEntries(formData.entries()));}

export async function registerPublicDayPassAction(_state:GuestRegistrationState,formData:FormData):Promise<GuestRegistrationState>{const parsed=registrationFields(formData);if(!parsed.success)return{status:"error",message:parsed.error.issues[0]?.message??"Check the registration"};const inviteToken=rawToken(),passToken=rawToken();try{const data=await privilegedAccess.registerPublicDayPass({...parsed.data,invitationTokenHash:hash(inviteToken),passReferenceHash:hash(passToken)});return result(inviteToken,passToken,data.validUntil,parsed.data.paymentChoice);}catch{return{status:"error",message:"Day-pass registration is unavailable or could not be completed."};}}

export async function createGuestPassAction(_state:GuestRegistrationState,formData:FormData):Promise<GuestRegistrationState>{const parsed=registrationFields(formData);if(!parsed.success)return{status:"error",message:parsed.error.issues[0]?.message??"Check the registration"};const{gym}=await requireActiveGymContext({gymSlug:parsed.data.gymSlug});const inviteToken=rawToken(),passToken=rawToken();const supabase=await createServerComponentSupabaseClient();const{data,error}=await supabase.rpc("create_guest_pass",{target_gym_id:gym.id,guest_full_name:parsed.data.guestName,guest_email:parsed.data.guestEmail,invitation_token_hash:hash(inviteToken),pass_reference_hash:hash(passToken),payment_choice:parsed.data.paymentChoice});if(error)return{status:"error",message:error.message.includes("Too many")?error.message:"Guest registration could not be created."};const validUntil=data&&typeof data==="object"&&!Array.isArray(data)&&typeof data.valid_until==="string"?data.valid_until:"";revalidatePath(`/g/${gym.slug}`);return result(inviteToken,passToken,validUntil,parsed.data.paymentChoice);}

export async function verifyGuestPassAction(_state:PassVerificationState,formData:FormData):Promise<PassVerificationState>{const fields=z.object({gymSlug:slug,reference:z.string()}).safeParse(Object.fromEntries(formData.entries()));if(!fields.success)return{status:"error",message:"Enter a pass reference."};let raw:string;try{raw=normalizeReference(fields.data.reference);}catch{return{status:"error",message:"The pass reference format is invalid."};}const{gym}=await requireActiveGymContext({gymSlug:fields.data.gymSlug,allowedRoles:["owner","staff"]});const supabase=await createServerComponentSupabaseClient();const{data,error}=await supabase.rpc("verify_guest_pass",{target_gym_id:gym.id,pass_reference_hash:hash(raw)});if(error||!data||typeof data!=="object"||Array.isArray(data))return{status:"error",message:"Pass verification failed."};const row=data as Record<string,unknown>;if(row.found!==true)return{status:"error",message:"No pass matches that reference.",reference:fields.data.reference,result:{found:false}};return{status:"success",message:"Pass found.",reference:fields.data.reference,result:{found:true,guestName:typeof row.guest_name==="string"?row.guest_name:undefined,passStatus:typeof row.status==="string"?row.status:undefined,paymentState:typeof row.payment_state==="string"?row.payment_state:undefined,waiversComplete:row.waivers_complete===true,validUntil:typeof row.valid_until==="string"?row.valid_until:undefined,registrationSource:typeof row.registration_source==="string"?row.registration_source:undefined}};}

export async function checkInGuestPassAction(_state:PassVerificationState,formData:FormData):Promise<PassVerificationState>{const fields=z.object({gymSlug:slug,reference:z.string()}).safeParse(Object.fromEntries(formData.entries()));if(!fields.success)return{status:"error",message:"Enter a pass reference."};let raw:string;try{raw=normalizeReference(fields.data.reference);}catch{return{status:"error",message:"The pass reference format is invalid."};}const{gym}=await requireActiveGymContext({gymSlug:fields.data.gymSlug,allowedRoles:["owner","staff"]});const supabase=await createServerComponentSupabaseClient();const{error}=await supabase.rpc("check_in_guest_pass",{target_gym_id:gym.id,pass_reference_hash:hash(raw),confirm_reception_payment:formData.get("confirmPayment")==="on"});if(error)return{status:"error",message:error.message};revalidatePath(`/g/${gym.slug}/staff/guests`);return{status:"success",message:"Guest checked in. This reference cannot be used again.",reference:fields.data.reference};}

export async function configureDayPassAction(formData:FormData){const parsed=z.object({gymSlug:slug,validHours:z.coerce.number().int().min(1).max(168),information:z.string().trim().max(2000)}).parse(Object.fromEntries(formData.entries()));const{gym}=await requireActiveGymContext({gymSlug:parsed.gymSlug,allowedRoles:["owner"]});const supabase=await createServerComponentSupabaseClient();await supabase.rpc("configure_day_pass_registration",{target_gym_id:gym.id,registration_enabled:formData.get("enabled")==="on",valid_hours:parsed.validHours,public_information:parsed.information});revalidatePath(`/g/${gym.slug}/staff/guests`);revalidatePath(`/visit/${gym.slug}`);}
export async function revokeGuestPassAction(formData:FormData){const parsed=z.object({gymSlug:slug,passId:z.uuid()}).parse(Object.fromEntries(formData.entries()));const{gym}=await requireActiveGymContext({gymSlug:parsed.gymSlug,allowedRoles:["owner","staff"]});const supabase=await createServerComponentSupabaseClient();await supabase.rpc("revoke_guest_pass",{target_gym_id:gym.id,target_pass_id:parsed.passId});revalidatePath(`/g/${gym.slug}/staff/guests`);}
