-- Prompt 31: maintainable plan definitions, server-side limits and non-destructive grace.
create table public.platform_plans(plan_key text primary key check(plan_key~'^[a-z][a-z0-9_-]*$'),name text not null,description text not null,features jsonb not null check(jsonb_typeof(features)='object'),display_order smallint not null,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create trigger platform_plans_set_updated_at before update on public.platform_plans for each row execute function public.set_updated_at();alter table public.platform_plans enable row level security;alter table public.platform_plans force row level security;create policy platform_plans_read on public.platform_plans for select to authenticated using(active);grant select on public.platform_plans to authenticated;grant all on public.platform_plans to service_role;
insert into public.platform_plans(plan_key,name,description,display_order,features)values
('starter','Starter','Core operations for a small gym.',1,'{"staff_seats":{"enabled":true,"limit":3},"active_members":{"enabled":true,"limit":250},"routes":{"enabled":true,"limit":200},"wall_images":{"enabled":true,"limit":10},"analytics":{"enabled":false},"chat":{"enabled":false},"custom_branding":{"enabled":false}}'),
('growth','Growth','Community and reporting for a growing gym.',2,'{"staff_seats":{"enabled":true,"limit":10},"active_members":{"enabled":true,"limit":1500},"routes":{"enabled":true,"limit":1000},"wall_images":{"enabled":true,"limit":50},"analytics":{"enabled":true},"chat":{"enabled":true},"custom_branding":{"enabled":false}}'),
('pro','Pro','Expanded limits, analytics, chat and custom branding.',3,'{"staff_seats":{"enabled":true,"limit":50},"active_members":{"enabled":true,"limit":10000},"routes":{"enabled":true,"limit":5000},"wall_images":{"enabled":true,"limit":250},"analytics":{"enabled":true},"chat":{"enabled":true},"custom_branding":{"enabled":true}}');
alter table public.subscriptions add column grace_ends_at timestamptz;

create or replace function private.prepare_subscription_grace()returns trigger language plpgsql security definer set search_path=''as $$begin if new.status in('past_due','canceled','unpaid')then if new.grace_ends_at is null or old.status is distinct from new.status then new.grace_ends_at:=greatest(coalesce(new.current_period_end,now()),now())+interval'7 days';end if;elsif new.status in('trialing','active')then new.grace_ends_at:=null;end if;return new;end$$;
create trigger subscriptions_prepare_grace before insert or update of status,current_period_end on public.subscriptions for each row execute function private.prepare_subscription_grace();
create or replace function private.sync_plan_entitlements()returns trigger language plpgsql security definer set search_path=''as $$declare feature record;plan_features jsonb;entitlement_end timestamptz;begin if exists(select 1 from public.subscriptions candidate where candidate.gym_id=new.gym_id and candidate.id<>new.id and(candidate.status in('trialing','active','past_due','paused','unpaid','incomplete')or(candidate.status='canceled'and candidate.created_at>new.created_at))and(candidate.created_at>new.created_at or(candidate.created_at=new.created_at and candidate.id>new.id)))then return new;end if;select features into plan_features from public.platform_plans where plan_key=new.plan_key and active;if plan_features is null then return new;end if;entitlement_end:=case when new.grace_ends_at is null or new.current_period_start is null then new.grace_ends_at else greatest(new.grace_ends_at,new.current_period_start+interval'1 microsecond')end;for feature in select key,value from jsonb_each(plan_features)loop insert into public.feature_entitlements(gym_id,subscription_id,feature_key,enabled,limit_value,source,starts_at,ends_at,metadata)values(new.gym_id,new.id,feature.key,coalesce((feature.value->>'enabled')::boolean,false),(feature.value->>'limit')::integer,'plan',new.current_period_start,entitlement_end,jsonb_build_object('plan_key',new.plan_key))on conflict(gym_id,feature_key)do update set subscription_id=excluded.subscription_id,enabled=excluded.enabled,limit_value=excluded.limit_value,source='plan',starts_at=excluded.starts_at,ends_at=excluded.ends_at,metadata=excluded.metadata where public.feature_entitlements.source='plan';end loop;return new;end$$;
create trigger subscriptions_sync_entitlements after insert or update of plan_key,status,current_period_start,current_period_end,grace_ends_at on public.subscriptions for each row execute function private.sync_plan_entitlements();

create or replace function private.feature_available(target_gym_id uuid,target_feature text)returns boolean language sql stable security definer set search_path=''as $$select case when not exists(select 1 from public.subscriptions where gym_id=target_gym_id)then true else coalesce((select entitlement.enabled and(subscription.status in('active','trialing')or(subscription.status in('past_due','canceled','unpaid')and coalesce(subscription.grace_ends_at,subscription.current_period_end)>now()))from public.feature_entitlements entitlement join public.subscriptions subscription on subscription.id=entitlement.subscription_id and subscription.gym_id=entitlement.gym_id where entitlement.gym_id=target_gym_id and entitlement.feature_key=target_feature),false)end$$;
create or replace function private.feature_limit(target_gym_id uuid,target_feature text)returns integer language sql stable security definer set search_path=''as $$select case when not exists(select 1 from public.subscriptions where gym_id=target_gym_id)then null else(select limit_value from public.feature_entitlements where gym_id=target_gym_id and feature_key=target_feature and private.feature_available(target_gym_id,target_feature))end$$;
revoke all on function private.feature_available(uuid,text),private.feature_limit(uuid,text)from public,anon,authenticated;
grant execute on function private.feature_available(uuid,text),private.feature_limit(uuid,text)to service_role;

create or replace function private.enforce_plan_feature()returns trigger language plpgsql security definer set search_path=''as $$declare feature text:=tg_argv[0];usage_count integer;allowed integer;adds_usage boolean;begin if not private.feature_available(new.gym_id,feature)then raise exception'Feature % is not available on this gym plan',feature using errcode='42501';end if;allowed:=private.feature_limit(new.gym_id,feature);if allowed is null then return new;end if;usage_count:=case feature when'staff_seats'then(select count(*)from public.gym_memberships where gym_id=new.gym_id and status='active'and role in('owner','staff','route_setter'))when'active_members'then(select count(*)from public.gym_memberships where gym_id=new.gym_id and status='active')when'routes'then(select count(*)from public.routes where gym_id=new.gym_id and archived_at is null)when'wall_images'then(select count(*)from public.wall_images where gym_id=new.gym_id and archived_at is null)else 0 end;adds_usage:=tg_op='INSERT'or(feature='staff_seats'and not(old.status='active'and old.role in('owner','staff','route_setter')))or(feature='active_members'and old.status<>'active');if adds_usage and usage_count>=allowed then raise exception'Plan limit reached for %',feature using errcode='23514';end if;return new;end$$;
create trigger plan_limit_staff before insert or update of status,role on public.gym_memberships for each row when(new.status='active'and new.role in('owner','staff','route_setter'))execute function private.enforce_plan_feature('staff_seats');
create trigger plan_limit_members before insert or update of status on public.gym_memberships for each row when(new.status='active')execute function private.enforce_plan_feature('active_members');
create trigger plan_limit_routes before insert on public.routes for each row execute function private.enforce_plan_feature('routes');create trigger plan_limit_wall_images before insert on public.wall_images for each row execute function private.enforce_plan_feature('wall_images');create trigger plan_gate_channels before insert on public.chat_channels for each row execute function private.enforce_plan_feature('chat');create trigger plan_gate_messages before insert on public.messages for each row execute function private.enforce_plan_feature('chat');
create or replace function private.enforce_branding_plan()returns trigger language plpgsql security definer set search_path=''as $$begin if(to_jsonb(old)-array['updated_at','created_at'])is distinct from(to_jsonb(new)-array['updated_at','created_at'])and not private.feature_available(new.gym_id,'custom_branding')then raise exception'Custom branding is not available on this gym plan'using errcode='42501';end if;return new;end$$;create trigger plan_gate_branding before update on public.gym_branding for each row execute function private.enforce_branding_plan();

create or replace function public.get_plan_usage(target_gym_id uuid)returns table(plan_key text,plan_name text,subscription_status text,grace_ends_at timestamptz,feature_key text,enabled boolean,limit_value integer,usage_value integer,restricted boolean)language sql stable security definer set search_path=''as $$select subscription.plan_key,plan.name,subscription.status,subscription.grace_ends_at,entitlement.feature_key,private.feature_available(target_gym_id,entitlement.feature_key),entitlement.limit_value,case entitlement.feature_key when'staff_seats'then(select count(*)::integer from public.gym_memberships where gym_id=target_gym_id and status='active'and role in('owner','staff','route_setter'))when'active_members'then(select count(*)::integer from public.gym_memberships where gym_id=target_gym_id and status='active')when'routes'then(select count(*)::integer from public.routes where gym_id=target_gym_id and archived_at is null)when'wall_images'then(select count(*)::integer from public.wall_images where gym_id=target_gym_id and archived_at is null)else 0 end,not private.feature_available(target_gym_id,entitlement.feature_key)from public.feature_entitlements entitlement join public.subscriptions subscription on subscription.id=entitlement.subscription_id and subscription.gym_id=entitlement.gym_id join public.platform_plans plan on plan.plan_key=subscription.plan_key where entitlement.gym_id=target_gym_id and private.has_gym_role(target_gym_id,array['owner'])order by entitlement.feature_key;$$;
revoke all on function public.get_plan_usage(uuid)from public,anon;grant execute on function public.get_plan_usage(uuid)to authenticated;
create or replace function public.has_feature_entitlement(target_gym_id uuid,target_feature text)returns boolean language sql stable security definer set search_path=''as $$select private.current_membership_id(target_gym_id)is not null and private.feature_available(target_gym_id,target_feature)$$;revoke all on function public.has_feature_entitlement(uuid,text)from public,anon;grant execute on function public.has_feature_entitlement(uuid,text)to authenticated;
