-- Prompt 26: registration, divisions, validated bouldering scoring and immutable finals.
alter table public.competitions add column registration_opens_at timestamptz;
alter table public.competitions add column registration_closes_at timestamptz;
alter table public.competitions add column attempt_limit smallint check(attempt_limit between 1 and 999);
alter table public.competitions add column finalized_at timestamptz;
alter table public.competitions add column finalized_by uuid references public.profiles(id);

create table public.competition_divisions(id uuid primary key default gen_random_uuid(),gym_id uuid not null references public.gyms(id)on delete cascade,competition_id uuid not null,name text not null check(char_length(name)between 1 and 80),eligibility jsonb not null default '{}'check(jsonb_typeof(eligibility)='object'),created_at timestamptz not null default now(),constraint competition_divisions_competition_fkey foreign key(competition_id,gym_id)references public.competitions(id,gym_id)on delete cascade,constraint competition_divisions_unique unique(competition_id,name),constraint competition_divisions_id_gym_key unique(id,gym_id));
create table public.competition_registrations(id uuid primary key default gen_random_uuid(),gym_id uuid not null references public.gyms(id)on delete cascade,competition_id uuid not null,division_id uuid not null,profile_id uuid not null references public.profiles(id)on delete cascade,status text not null default 'registered'check(status in('registered','withdrawn','disqualified')),registered_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint competition_registrations_competition_fkey foreign key(competition_id,gym_id)references public.competitions(id,gym_id)on delete cascade,constraint competition_registrations_division_fkey foreign key(division_id,gym_id)references public.competition_divisions(id,gym_id),constraint competition_registrations_unique unique(competition_id,profile_id),constraint competition_registrations_id_gym_key unique(id,gym_id));
create table public.score_entry_history(id uuid primary key default gen_random_uuid(),gym_id uuid not null references public.gyms(id)on delete cascade,score_entry_id uuid not null,competition_id uuid not null,changed_by uuid not null references public.profiles(id),change_reason text not null check(char_length(change_reason)between 3 and 1000),before_value jsonb,after_value jsonb not null,created_at timestamptz not null default now(),constraint score_history_entry_fkey foreign key(score_entry_id,gym_id)references public.score_entries(id,gym_id)on delete cascade);
create index competition_registrations_competition_idx on public.competition_registrations(gym_id,competition_id,status);
create index competition_divisions_gym_competition_idx on public.competition_divisions(gym_id,competition_id);
create index score_entry_history_competition_idx on public.score_entry_history(gym_id,competition_id,created_at desc);
create trigger competition_registrations_set_updated_at before update on public.competition_registrations for each row execute function public.set_updated_at();

alter table public.competition_divisions enable row level security;alter table public.competition_divisions force row level security;
alter table public.competition_registrations enable row level security;alter table public.competition_registrations force row level security;
alter table public.score_entry_history enable row level security;alter table public.score_entry_history force row level security;
create policy competition_divisions_read on public.competition_divisions for select to authenticated using(private.current_membership_id(gym_id)is not null);
create policy competition_divisions_rpc on public.competition_divisions for all to authenticated using(false)with check(false);
create policy competition_registrations_read on public.competition_registrations for select to authenticated using(profile_id=auth.uid()or private.has_gym_capability(gym_id,'competitions.manage')or private.has_gym_capability(gym_id,'competitions.score'));
create policy competition_registrations_rpc on public.competition_registrations for all to authenticated using(false)with check(false);
create policy score_entry_history_staff on public.score_entry_history for select to authenticated using(private.has_gym_capability(gym_id,'competitions.manage')or private.has_gym_capability(gym_id,'competitions.score'));
create policy score_entry_history_rpc on public.score_entry_history for insert to authenticated with check(false);
grant select on public.competition_divisions,public.competition_registrations,public.score_entry_history to authenticated;

drop policy competitions_insert_staff on public.competitions;drop policy competitions_update_staff on public.competitions;drop policy competitions_delete_staff on public.competitions;
create policy competitions_rpc_insert on public.competitions for insert to authenticated with check(false);create policy competitions_rpc_update on public.competitions for update to authenticated using(false);
drop policy competition_routes_manage_staff on public.competition_routes;create policy competition_routes_rpc on public.competition_routes for all to authenticated using(false)with check(false);
drop policy score_entries_insert_staff on public.score_entries;drop policy score_entries_update_staff on public.score_entries;
create policy score_entries_rpc_insert on public.score_entries for insert to authenticated with check(false);create policy score_entries_rpc_update on public.score_entries for update to authenticated using(false);

create or replace function public.save_competition(target_gym_id uuid,target_competition_id uuid,competition_name text,competition_description text,window_start timestamptz,window_end timestamptz,registration_start timestamptz,registration_end timestamptz,competition_status text,maximum_attempts smallint,division_names text[])
returns uuid language plpgsql security definer set search_path=''as $$declare saved_id uuid;division_name text;begin
if not private.has_gym_capability(target_gym_id,'competitions.manage')then raise insufficient_privilege;end if;
competition_name:=btrim(competition_name);if char_length(competition_name)not between 1 and 160 or window_end<=window_start or registration_end>window_end or registration_end<=registration_start or competition_status not in('draft','registration','live')or maximum_attempts not between 1 and 999 or cardinality(division_names)<1 then raise exception'Competition details are invalid'using errcode='22023';end if;
if target_competition_id is null then insert into public.competitions(gym_id,created_by,name,description,format,scoring_rules,status,starts_at,ends_at,registration_opens_at,registration_closes_at,attempt_limit,published_at)values(target_gym_id,auth.uid(),competition_name,nullif(btrim(competition_description),''),'tops_zones',jsonb_build_object('strategy','tops_zones_attempts_v1'),competition_status,window_start,window_end,registration_start,registration_end,maximum_attempts,case when competition_status<>'draft'then now()end)returning id into saved_id;else update public.competitions set name=competition_name,description=nullif(btrim(competition_description),''),status=competition_status,starts_at=window_start,ends_at=window_end,registration_opens_at=registration_start,registration_closes_at=registration_end,attempt_limit=maximum_attempts,published_at=case when competition_status<>'draft'then coalesce(published_at,now())end where id=target_competition_id and gym_id=target_gym_id and finalized_at is null returning id into saved_id;if saved_id is null then raise exception'Competition cannot be changed';end if;end if;
foreach division_name in array division_names loop division_name:=btrim(division_name);if char_length(division_name)not between 1 and 80 then raise exception'Invalid division';end if;insert into public.competition_divisions(gym_id,competition_id,name)values(target_gym_id,saved_id,division_name)on conflict(competition_id,name)do nothing;end loop;return saved_id;end$$;

create or replace function public.add_competition_route(target_gym_id uuid,target_competition_id uuid,target_route_id uuid)
returns uuid language plpgsql security definer set search_path=''as $$declare added_id uuid;begin if not private.has_gym_capability(target_gym_id,'competitions.manage')then raise insufficient_privilege;end if;if not exists(select 1 from public.competitions where id=target_competition_id and gym_id=target_gym_id and finalized_at is null)or not exists(select 1 from public.routes where id=target_route_id and gym_id=target_gym_id and route_type='boulder'and status='published')then raise exception'Only a published gym boulder can be added';end if;insert into public.competition_routes(gym_id,competition_id,route_id,sort_order)values(target_gym_id,target_competition_id,target_route_id,(select count(*)from public.competition_routes where competition_id=target_competition_id))on conflict(competition_id,route_id)do update set route_id=excluded.route_id returning id into added_id;return added_id;end$$;

create or replace function public.register_for_competition(target_gym_id uuid,target_competition_id uuid,target_division_id uuid)
returns uuid language plpgsql security definer set search_path=''as $$declare registration_id uuid;selected public.competitions;begin select*into selected from public.competitions where id=target_competition_id and gym_id=target_gym_id;if selected.id is null or selected.status<>'registration'or now()not between selected.registration_opens_at and selected.registration_closes_at or private.current_membership_id(target_gym_id)is null or not exists(select 1 from public.competition_divisions where id=target_division_id and competition_id=selected.id and gym_id=target_gym_id)then raise exception'Registration is not available';end if;insert into public.competition_registrations(gym_id,competition_id,division_id,profile_id)values(target_gym_id,selected.id,target_division_id,auth.uid())on conflict(competition_id,profile_id)do update set division_id=excluded.division_id,status='registered' returning id into registration_id;return registration_id;end$$;

create or replace function public.submit_competition_score(target_gym_id uuid,target_competition_id uuid,target_competition_route_id uuid,target_profile_id uuid,top_achieved boolean,zone_achieved boolean,attempt_count smallint,correction_reason text default null)
returns uuid language plpgsql security definer set search_path=''as $$declare selected public.competitions;entry public.score_entries;calculated numeric;can_score boolean;begin
select*into selected from public.competitions where id=target_competition_id and gym_id=target_gym_id;can_score:=private.has_gym_capability(target_gym_id,'competitions.manage')or private.has_gym_capability(target_gym_id,'competitions.score');
if selected.id is null or selected.status<>'live'or selected.finalized_at is not null or now()not between selected.starts_at and selected.ends_at or attempt_count<1 or attempt_count>selected.attempt_limit or(target_profile_id<>auth.uid()and not can_score)or not exists(select 1 from public.competition_registrations where competition_id=selected.id and profile_id=target_profile_id and status='registered')or not exists(select 1 from public.competition_routes where id=target_competition_route_id and competition_id=selected.id and gym_id=target_gym_id)then raise exception'Score is outside competition eligibility or window rules';end if;
if top_achieved then zone_achieved:=true;end if;calculated:=(case when top_achieved then 10000 else 0 end)+(case when zone_achieved then 1000 else 0 end)-attempt_count;
select*into entry from public.score_entries where competition_route_id=target_competition_route_id and profile_id=target_profile_id and voided_at is null;
if entry.id is null then insert into public.score_entries(gym_id,competition_id,competition_route_id,profile_id,recorded_by,score,attempts,topped,zone_reached)values(target_gym_id,selected.id,target_competition_route_id,target_profile_id,auth.uid(),calculated,attempt_count,top_achieved,zone_achieved)returning*into entry;insert into public.score_entry_history(gym_id,score_entry_id,competition_id,changed_by,change_reason,before_value,after_value)values(target_gym_id,entry.id,selected.id,auth.uid(),'Initial score',null,to_jsonb(entry));else if char_length(btrim(coalesce(correction_reason,'')))<3 then raise exception'A correction reason is required';end if;insert into public.score_entry_history(gym_id,score_entry_id,competition_id,changed_by,change_reason,before_value,after_value)values(target_gym_id,entry.id,selected.id,auth.uid(),btrim(correction_reason),to_jsonb(entry),jsonb_build_object('score',calculated,'attempts',attempt_count,'topped',top_achieved,'zone_reached',zone_achieved));update public.score_entries set score=calculated,attempts=attempt_count,topped=top_achieved,zone_reached=zone_achieved,recorded_by=auth.uid(),recorded_at=now()where id=entry.id;end if;return entry.id;end$$;

create or replace function public.finalize_competition(target_gym_id uuid,target_competition_id uuid)
returns uuid language plpgsql security definer set search_path=''as $$begin if not private.has_gym_capability(target_gym_id,'competitions.manage')then raise insufficient_privilege;end if;update public.competitions set status='complete',finalized_at=now(),finalized_by=auth.uid()where id=target_competition_id and gym_id=target_gym_id and finalized_at is null and status='live';if not found then raise exception'Only a live competition can be finalized';end if;insert into public.audit_logs(gym_id,actor_profile_id,actor_type,action,target_type,target_id,metadata)values(target_gym_id,auth.uid(),'user','competition.finalized','competition',target_competition_id,'{}');return target_competition_id;end$$;

revoke all on function public.save_competition(uuid,uuid,text,text,timestamptz,timestamptz,timestamptz,timestamptz,text,smallint,text[]),public.add_competition_route(uuid,uuid,uuid),public.register_for_competition(uuid,uuid,uuid),public.submit_competition_score(uuid,uuid,uuid,uuid,boolean,boolean,smallint,text),public.finalize_competition(uuid,uuid)from public,anon;
grant execute on function public.save_competition(uuid,uuid,text,text,timestamptz,timestamptz,timestamptz,timestamptz,text,smallint,text[]),public.add_competition_route(uuid,uuid,uuid),public.register_for_competition(uuid,uuid,uuid),public.submit_competition_score(uuid,uuid,uuid,uuid,boolean,boolean,smallint,text),public.finalize_competition(uuid,uuid)to authenticated;
do $$begin if exists(select 1 from pg_publication where pubname='supabase_realtime')and not exists(select 1 from pg_publication_tables where pubname='supabase_realtime'and schemaname='public'and tablename='score_entries')then alter publication supabase_realtime add table public.score_entries;end if;end$$;
