-- Prompt 23: moderated community feed with audited reports and hidden-safe engagement.
alter table public.community_posts add column image_path text;
alter table public.community_posts add column is_pinned boolean not null default false;
alter table public.community_posts add column locked_at timestamptz;
alter table public.community_posts add column moderation_reason text check(moderation_reason is null or char_length(moderation_reason)<=1000);
alter table public.community_posts add constraint community_posts_image_path_check check(image_path is null or image_path ~ ('^'||gym_id::text||'/[0-9a-f-]{36}\.(png|jpg|webp)$'));
alter table public.comments add column moderation_reason text check(moderation_reason is null or char_length(moderation_reason)<=1000);

create table public.community_guideline_acceptances(gym_id uuid not null references public.gyms(id)on delete cascade,profile_id uuid not null references public.profiles(id)on delete cascade,version text not null default '2026-01',accepted_at timestamptz not null default now(),primary key(gym_id,profile_id,version));
create table public.community_reports(id uuid primary key default gen_random_uuid(),gym_id uuid not null references public.gyms(id)on delete cascade,reporter_id uuid not null references public.profiles(id)on delete cascade,post_id uuid,comment_id uuid,reason text not null check(char_length(trim(reason))between 3 and 1000),status text not null default 'open' check(status in('open','reviewed','dismissed','actioned')),created_at timestamptz not null default now(),constraint community_reports_post_fkey foreign key(post_id,gym_id)references public.community_posts(id,gym_id),constraint community_reports_comment_fkey foreign key(comment_id,gym_id)references public.comments(id,gym_id),constraint community_reports_target_check check(num_nonnulls(post_id,comment_id)=1),constraint community_reports_unique unique(reporter_id,post_id,comment_id));
create index community_reports_gym_status_idx on public.community_reports(gym_id,status,created_at);
create unique index community_reports_post_once_idx on public.community_reports(reporter_id,post_id)where post_id is not null;create unique index community_reports_comment_once_idx on public.community_reports(reporter_id,comment_id)where comment_id is not null;
create table public.community_blocks(gym_id uuid not null references public.gyms(id)on delete cascade,blocker_id uuid not null references public.profiles(id)on delete cascade,blocked_id uuid not null references public.profiles(id)on delete cascade,created_at timestamptz not null default now(),primary key(gym_id,blocker_id,blocked_id),check(blocker_id<>blocked_id));
create table public.community_mutes(gym_id uuid not null references public.gyms(id)on delete cascade,profile_id uuid not null references public.profiles(id)on delete cascade,muted_profile_id uuid not null references public.profiles(id)on delete cascade,expires_at timestamptz,created_at timestamptz not null default now(),primary key(gym_id,profile_id,muted_profile_id),check(profile_id<>muted_profile_id));
alter table public.community_guideline_acceptances enable row level security;alter table public.community_reports enable row level security;alter table public.community_blocks enable row level security;alter table public.community_mutes enable row level security;alter table public.community_guideline_acceptances force row level security;alter table public.community_reports force row level security;alter table public.community_blocks force row level security;alter table public.community_mutes force row level security;
grant select on public.community_guideline_acceptances,public.community_reports,public.community_blocks,public.community_mutes to authenticated;grant all on public.community_guideline_acceptances,public.community_reports,public.community_blocks,public.community_mutes to service_role;
create policy guideline_acceptances_self on public.community_guideline_acceptances for select to authenticated using(profile_id=auth.uid());create policy community_reports_self_or_moderator on public.community_reports for select to authenticated using(reporter_id=auth.uid() or private.has_gym_capability(gym_id,'community.moderate'));create policy community_blocks_self on public.community_blocks for select to authenticated using(blocker_id=auth.uid());create policy community_mutes_self on public.community_mutes for select to authenticated using(profile_id=auth.uid());

drop policy community_posts_insert_self on public.community_posts;drop policy community_posts_update_self_or_moderator on public.community_posts;drop policy comments_insert_self on public.comments;drop policy comments_update_self_or_moderator on public.comments;drop policy reactions_insert_self on public.reactions;drop policy reactions_delete_self on public.reactions;
revoke insert,update,delete on public.community_posts,public.comments,public.reactions from authenticated;
drop policy reactions_select_member on public.reactions;
drop policy comments_select_member on public.comments;
create policy comments_select_visible_parent on public.comments for select to authenticated using(private.current_membership_id(gym_id)is not null and((moderation_status='visible'and deleted_at is null and exists(select 1 from public.community_posts post where post.id=post_id and post.gym_id=comments.gym_id and post.moderation_status='visible'and post.deleted_at is null))or author_id=auth.uid()or private.has_gym_capability(gym_id,'community.moderate')));
create policy reactions_select_visible_target on public.reactions for select to authenticated using(private.current_membership_id(gym_id)is not null and((post_id is not null and exists(select 1 from public.community_posts post where post.id=post_id and post.gym_id=reactions.gym_id and post.moderation_status='visible' and post.deleted_at is null))or(comment_id is not null and exists(select 1 from public.comments comment join public.community_posts post on post.id=comment.post_id and post.gym_id=comment.gym_id where comment.id=comment_id and comment.gym_id=reactions.gym_id and comment.moderation_status='visible' and comment.deleted_at is null and post.moderation_status='visible' and post.deleted_at is null))));

create or replace function public.accept_community_guidelines(target_gym_id uuid)
returns uuid language plpgsql security definer set search_path='' as $$begin if private.current_membership_id(target_gym_id)is null then raise exception 'Active membership is required'using errcode='42501';end if;insert into public.community_guideline_acceptances(gym_id,profile_id)values(target_gym_id,auth.uid())on conflict do nothing;return auth.uid();end;$$;
create or replace function public.create_community_post(target_gym_id uuid,post_title text,post_body text,post_image_path text)
returns uuid language plpgsql security definer set search_path='' as $$declare post_id uuid;begin if private.current_membership_id(target_gym_id)is null or not exists(select 1 from public.community_guideline_acceptances where gym_id=target_gym_id and profile_id=auth.uid() and version='2026-01')then raise exception 'Accept the community guidelines first'using errcode='42501';end if;if char_length(trim(post_body))not between 1 and 10000 or char_length(coalesce(trim(post_title),''))>200 or(post_image_path is not null and post_image_path!~('^'||target_gym_id::text||'/[0-9a-f-]{36}\.(png|jpg|webp)$'))then raise exception 'Post details are invalid'using errcode='22023';end if;perform private.consume_action_limit(target_gym_id,'community_post',5,3600);insert into public.community_posts(gym_id,author_id,title,body,image_path)values(target_gym_id,auth.uid(),nullif(trim(post_title),''),trim(post_body),post_image_path)returning id into post_id;return post_id;end;$$;
create or replace function public.create_community_comment(target_gym_id uuid,target_post_id uuid,comment_body text)
returns uuid language plpgsql security definer set search_path='' as $$declare comment_id uuid;begin if char_length(trim(comment_body))not between 1 and 5000 or not exists(select 1 from public.community_posts where id=target_post_id and gym_id=target_gym_id and moderation_status='visible' and deleted_at is null and locked_at is null)then raise exception 'Comment is invalid or the post is locked'using errcode='22023';end if;perform private.consume_action_limit(target_gym_id,'community_comment',30,3600);insert into public.comments(gym_id,post_id,author_id,body)values(target_gym_id,target_post_id,auth.uid(),trim(comment_body))returning id into comment_id;return comment_id;end;$$;
create or replace function public.toggle_community_reaction(target_gym_id uuid,target_post_id uuid,reaction_name text)
returns boolean language plpgsql security definer set search_path='' as $$begin if reaction_name not in('like','love','strong','celebrate','support')or not exists(select 1 from public.community_posts where id=target_post_id and gym_id=target_gym_id and moderation_status='visible'and deleted_at is null)then raise exception 'Reaction target is unavailable'using errcode='22023';end if;perform private.consume_action_limit(target_gym_id,'community_reaction',120,3600);if exists(select 1 from public.reactions where post_id=target_post_id and profile_id=auth.uid()and reaction=reaction_name)then delete from public.reactions where post_id=target_post_id and profile_id=auth.uid()and reaction=reaction_name;return false;end if;insert into public.reactions(gym_id,profile_id,post_id,reaction)values(target_gym_id,auth.uid(),target_post_id,reaction_name);return true;end;$$;
create or replace function public.delete_community_content(target_gym_id uuid,target_type text,target_id uuid)
returns uuid language plpgsql security definer set search_path='' as $$declare affected uuid;begin if target_type='post'then update public.community_posts set deleted_at=now()where id=target_id and gym_id=target_gym_id and author_id=auth.uid()returning id into affected;elsif target_type='comment'then update public.comments set deleted_at=now()where id=target_id and gym_id=target_gym_id and author_id=auth.uid()returning id into affected;end if;if affected is null then raise exception 'Owned content was not found'using errcode='22023';end if;insert into public.audit_logs(gym_id,actor_profile_id,actor_type,action,target_type,target_id)values(target_gym_id,auth.uid(),'user','community.content.deleted',target_type,target_id);return affected;end;$$;
create or replace function public.report_community_content(target_gym_id uuid,target_type text,target_id uuid,report_reason text)
returns uuid language plpgsql security definer set search_path='' as $$declare report_id uuid;begin if private.current_membership_id(target_gym_id)is null or char_length(trim(report_reason))not between 3 and 1000 or not((target_type='post'and exists(select 1 from public.community_posts where id=target_id and gym_id=target_gym_id))or(target_type='comment'and exists(select 1 from public.comments where id=target_id and gym_id=target_gym_id)))then raise exception 'Report is invalid'using errcode='22023';end if;insert into public.community_reports(gym_id,reporter_id,post_id,comment_id,reason)values(target_gym_id,auth.uid(),case when target_type='post'then target_id end,case when target_type='comment'then target_id end,trim(report_reason))returning id into report_id;insert into public.audit_logs(gym_id,actor_profile_id,actor_type,action,target_type,target_id,metadata)values(target_gym_id,auth.uid(),'user','community.content.reported',target_type,target_id,jsonb_build_object('report_id',report_id));return report_id;exception when unique_violation then raise exception 'You have already reported this content'using errcode='23505';end;$$;
create or replace function public.moderate_community_post(target_gym_id uuid,target_post_id uuid,target_status text,lock_post boolean,reason text,pin_post boolean)
returns uuid language plpgsql security definer set search_path='' as $$begin if not private.has_gym_capability(target_gym_id,'community.moderate')or target_status not in('visible','hidden','removed')or char_length(trim(reason))not between 3 and 1000 then raise exception 'Moderation request is invalid'using errcode='42501';end if;update public.community_posts set moderation_status=target_status,moderation_reason=trim(reason),locked_at=case when lock_post then coalesce(locked_at,now())else null end,is_pinned=pin_post where id=target_post_id and gym_id=target_gym_id;if not found then raise exception 'Post was not found'using errcode='22023';end if;insert into public.audit_logs(gym_id,actor_profile_id,actor_type,action,target_type,target_id,metadata)values(target_gym_id,auth.uid(),'user','community.post.moderated','community_post',target_post_id,jsonb_build_object('status',target_status,'locked',lock_post,'pinned',pin_post,'reason',trim(reason)));return target_post_id;end;$$;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)values('community-images','community-images',false,10485760,array['image/png','image/jpeg','image/webp'])on conflict(id)do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy community_images_select on storage.objects for select to authenticated using(bucket_id='community-images'and exists(select 1 from public.community_posts post where post.image_path=name));create policy community_images_insert on storage.objects for insert to authenticated with check(bucket_id='community-images'and private.current_membership_id((storage.foldername(name))[1]::uuid)is not null);create policy community_images_delete on storage.objects for delete to authenticated using(bucket_id='community-images'and exists(select 1 from public.community_posts post where post.image_path=name and post.author_id=auth.uid()));
revoke all on function public.accept_community_guidelines(uuid)from public,anon;revoke all on function public.create_community_post(uuid,text,text,text)from public,anon;revoke all on function public.create_community_comment(uuid,uuid,text)from public,anon;revoke all on function public.toggle_community_reaction(uuid,uuid,text)from public,anon;revoke all on function public.delete_community_content(uuid,text,uuid)from public,anon;revoke all on function public.report_community_content(uuid,text,uuid,text)from public,anon;revoke all on function public.moderate_community_post(uuid,uuid,text,boolean,text,boolean)from public,anon;
grant execute on function public.accept_community_guidelines(uuid),public.create_community_post(uuid,text,text,text),public.create_community_comment(uuid,uuid,text),public.toggle_community_reaction(uuid,uuid,text),public.delete_community_content(uuid,text,uuid),public.report_community_content(uuid,text,uuid,text),public.moderate_community_post(uuid,uuid,text,boolean,text,boolean)to authenticated,service_role;
