-- Prompt 34: bounded, permission-aware tenant search.
create extension if not exists pg_trgm with schema extensions;
create index routes_search_idx on public.routes using gin(to_tsvector('simple'::regconfig,coalesce(name,'')||' '||colour||' '||grade||' '||coalesce(description,'')))where status='published'and archived_at is null;
create index events_search_idx on public.events using gin(to_tsvector('simple'::regconfig,title||' '||coalesce(description,'')||' '||coalesce(location,'')))where status='published'and archived_at is null;
create index announcements_search_idx on public.announcements using gin(to_tsvector('simple'::regconfig,title||' '||body))where status='published'and archived_at is null;
create index community_posts_search_idx on public.community_posts using gin(to_tsvector('simple'::regconfig,coalesce(title,'')||' '||body))where moderation_status='visible'and deleted_at is null;
create index profiles_display_name_search_idx on public.profiles using gin(lower(display_name) extensions.gin_trgm_ops)where deleted_at is null and suspended_at is null;

create or replace function public.search_gym_content(target_gym_id uuid,search_query text,result_limit integer default 30)
returns table(result_kind text,result_id uuid,title text,snippet text,path text,rank real)language plpgsql stable security definer set search_path=''
as $$declare query tsquery;staff_access boolean;begin
  if private.current_membership_id(target_gym_id)is null then raise insufficient_privilege;end if;
  if char_length(btrim(search_query))not between 2 and 100 or result_limit not between 1 and 50 then raise exception'Invalid search request'using errcode='22023';end if;
  query:=websearch_to_tsquery('simple',btrim(search_query));staff_access:=private.has_gym_role(target_gym_id,array['owner','staff','route_setter']);
  return query with candidates as(
    select'route'::text kind,route.id,coalesce(route.name,route.colour||' '||route.grade)heading,left(coalesce(route.description,route.colour||' · '||route.grade),240)summary,'/routes/'||route.id path,ts_rank(to_tsvector('simple',coalesce(route.name,'')||' '||route.colour||' '||route.grade||' '||coalesce(route.description,'')),query)::real score from public.routes route where route.gym_id=target_gym_id and route.status='published'and route.archived_at is null and to_tsvector('simple',coalesce(route.name,'')||' '||route.colour||' '||route.grade||' '||coalesce(route.description,''))@@query
    union all select'event',event.id,event.title,left(coalesce(event.description,event.location,''),240),'/events/'||event.id,ts_rank(to_tsvector('simple',event.title||' '||coalesce(event.description,'')||' '||coalesce(event.location,'')),query)::real from public.events event where event.gym_id=target_gym_id and event.status='published'and event.archived_at is null and(event.visibility<>'staff'or staff_access)and to_tsvector('simple',event.title||' '||coalesce(event.description,'')||' '||coalesce(event.location,''))@@query
    union all select'announcement',announcement.id,announcement.title,left(announcement.body,240),'/announcements#announcement-'||announcement.id,ts_rank(to_tsvector('simple',announcement.title||' '||announcement.body),query)::real from public.announcements announcement where announcement.gym_id=target_gym_id and announcement.status='published'and announcement.archived_at is null and(announcement.audience<>'staff'or staff_access)and to_tsvector('simple',announcement.title||' '||announcement.body)@@query
    union all select'post',post.id,coalesce(post.title,'Community post'),left(post.body,240),'/community#post-'||post.id,ts_rank(to_tsvector('simple',coalesce(post.title,'')||' '||post.body),query)::real from public.community_posts post where post.gym_id=target_gym_id and post.moderation_status='visible'and post.deleted_at is null and(post.visibility<>'staff'or staff_access)and to_tsvector('simple',coalesce(post.title,'')||' '||post.body)@@query
    union all select'member',profile.id,profile.display_name,'Gym member','/community',greatest(extensions.similarity(lower(profile.display_name),lower(btrim(search_query))),0.01)::real from public.profiles profile join public.gym_memberships membership on membership.profile_id=profile.id and membership.gym_id=target_gym_id and membership.status='active'where profile.deleted_at is null and profile.suspended_at is null and lower(profile.display_name)like'%'||lower(btrim(search_query))||'%'
  )select candidates.kind,candidates.id,candidates.heading,candidates.summary,candidates.path,candidates.score from candidates order by candidates.score desc,candidates.heading limit result_limit;
end$$;
revoke all on function public.search_gym_content(uuid,text,integer)from public,anon;grant execute on function public.search_gym_content(uuid,text,integer)to authenticated;
