-- Prompt 24: expiring partner requests with private exact details and accepted conversations.
alter table public.chat_channels drop constraint chat_channels_channel_type_check;alter table public.chat_channels add constraint chat_channels_channel_type_check check(channel_type in('community','staff','event','competition','partner'));
alter table public.partner_requests add column window_ends_at timestamptz;
alter table public.partner_requests add column discipline text check(discipline in('bouldering','sport','top_rope','trad','training'));
alter table public.partner_requests add column approximate_ability text check(approximate_ability in('beginner','intermediate','advanced','open'));
alter table public.partner_requests add column session_intent text check(session_intent in('social','training','projecting','belay_partner','open'));
alter table public.partner_requests add column availability_note text check(availability_note is null or char_length(availability_note)<=1000);
alter table public.partner_requests add constraint partner_requests_window_check check(window_ends_at is null or climbing_date is null or window_ends_at>climbing_date);
create table public.partner_interests(id uuid primary key default gen_random_uuid(),gym_id uuid not null references public.gyms(id)on delete cascade,request_id uuid not null,profile_id uuid not null references public.profiles(id)on delete cascade,note text check(note is null or char_length(note)<=1000),status text not null default 'pending'check(status in('pending','accepted','declined','withdrawn')),conversation_channel_id uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint partner_interests_request_fkey foreign key(request_id,gym_id)references public.partner_requests(id,gym_id)on delete cascade,constraint partner_interests_channel_fkey foreign key(conversation_channel_id,gym_id)references public.chat_channels(id,gym_id),constraint partner_interests_unique unique(request_id,profile_id),constraint partner_interests_id_gym_key unique(id,gym_id));
create index partner_interests_gym_request_idx on public.partner_interests(gym_id,request_id,status);create trigger partner_interests_set_updated_at before update on public.partner_interests for each row execute function public.set_updated_at();
create table public.partner_request_reports(id uuid primary key default gen_random_uuid(),gym_id uuid not null references public.gyms(id)on delete cascade,request_id uuid not null,reporter_id uuid not null references public.profiles(id)on delete cascade,reason text not null check(char_length(trim(reason))between 3 and 1000),created_at timestamptz not null default now(),constraint partner_reports_request_fkey foreign key(request_id,gym_id)references public.partner_requests(id,gym_id),constraint partner_reports_once unique(request_id,reporter_id));create index partner_reports_gym_idx on public.partner_request_reports(gym_id,created_at);
alter table public.partner_interests enable row level security;alter table public.partner_interests force row level security;alter table public.partner_request_reports enable row level security;alter table public.partner_request_reports force row level security;grant select on public.partner_interests,public.partner_request_reports to authenticated;grant all on public.partner_interests,public.partner_request_reports to service_role;
create policy partner_interests_participants on public.partner_interests for select to authenticated using(profile_id=auth.uid()or exists(select 1 from public.partner_requests request where request.id=request_id and request.profile_id=auth.uid())or private.has_gym_capability(gym_id,'community.moderate'));create policy partner_reports_self_moderator on public.partner_request_reports for select to authenticated using(reporter_id=auth.uid()or private.has_gym_capability(gym_id,'community.moderate'));
drop policy partner_requests_select_member on public.partner_requests;drop policy partner_requests_insert_self on public.partner_requests;drop policy partner_requests_update_self_or_moderator on public.partner_requests;revoke select,insert,update,delete on public.partner_requests from authenticated;
create policy partner_requests_rpc_only on public.partner_requests for select to authenticated using(false);

create or replace function public.create_partner_request(target_gym_id uuid,window_start timestamptz,window_end timestamptz,discipline_name text,ability_name text,intent_name text,public_note text,private_availability text)
returns uuid language plpgsql security definer set search_path='' as $$declare request_id uuid;begin if private.current_membership_id(target_gym_id)is null or window_start<=now()or window_end<=window_start or window_end>now()+interval'30 days'or discipline_name not in('bouldering','sport','top_rope','trad','training')or ability_name not in('beginner','intermediate','advanced','open')or intent_name not in('social','training','projecting','belay_partner','open')or char_length(trim(public_note))not between 1 and 3000 or char_length(coalesce(private_availability,''))>1000 then raise exception'Partner request is invalid'using errcode='22023';end if;perform private.consume_action_limit(target_gym_id,'partner_request',5,86400);insert into public.partner_requests(gym_id,profile_id,title,body,climbing_date,window_ends_at,disciplines,discipline,approximate_ability,session_intent,availability_note,expires_at)values(target_gym_id,auth.uid(),'Looking for a climbing partner',trim(public_note),window_start,window_end,array[discipline_name],discipline_name,ability_name,intent_name,nullif(trim(private_availability),''),window_end)returning id into request_id;return request_id;end;$$;
create or replace function public.get_partner_requests(target_gym_id uuid)
returns table(id uuid,profile_id uuid,public_name text,climbing_day date,discipline text,approximate_ability text,session_intent text,body text,status text,exact_start timestamptz,exact_end timestamptz,availability_note text,is_owner boolean)language sql security definer stable set search_path='' as $$select request.id,request.profile_id,profile.display_name,request.climbing_date::date,request.discipline,request.approximate_ability,request.session_intent,request.body,request.status,case when request.profile_id=auth.uid()or exists(select 1 from public.partner_interests interest where interest.request_id=request.id and interest.profile_id=auth.uid()and interest.status='accepted')then request.climbing_date end,case when request.profile_id=auth.uid()or exists(select 1 from public.partner_interests interest where interest.request_id=request.id and interest.profile_id=auth.uid()and interest.status='accepted')then request.window_ends_at end,case when request.profile_id=auth.uid()or exists(select 1 from public.partner_interests interest where interest.request_id=request.id and interest.profile_id=auth.uid()and interest.status='accepted')then request.availability_note end,request.profile_id=auth.uid()from public.partner_requests request join public.profiles profile on profile.id=request.profile_id where request.gym_id=target_gym_id and private.current_membership_id(target_gym_id)is not null and((request.status='open'and request.expires_at>now())or request.profile_id=auth.uid()or exists(select 1 from public.partner_interests i where i.request_id=request.id and i.profile_id=auth.uid()))order by request.created_at desc limit 100$$;
create or replace function public.express_partner_interest(target_gym_id uuid,target_request_id uuid,interest_note text)
returns uuid language plpgsql security definer set search_path='' as $$declare interest_id uuid;begin if char_length(coalesce(interest_note,''))>1000 or not exists(select 1 from public.partner_requests where id=target_request_id and gym_id=target_gym_id and profile_id<>auth.uid()and status='open'and expires_at>now())then raise exception'Request is unavailable'using errcode='22023';end if;perform private.consume_action_limit(target_gym_id,'partner_interest',20,86400);insert into public.partner_interests(gym_id,request_id,profile_id,note)values(target_gym_id,target_request_id,auth.uid(),nullif(trim(interest_note),''))on conflict(request_id,profile_id)do update set status='pending',note=excluded.note returning id into interest_id;return interest_id;end;$$;
create or replace function public.respond_partner_interest(target_gym_id uuid,target_interest_id uuid,accept_interest boolean)
returns uuid language plpgsql security definer set search_path='' as $$declare interest public.partner_interests;request public.partner_requests;channel_id uuid;begin select*into interest from public.partner_interests where id=target_interest_id and gym_id=target_gym_id for update;select*into request from public.partner_requests where id=interest.request_id and profile_id=auth.uid()for update;if request.id is null or interest.status<>'pending'then raise exception'Interest response is unavailable'using errcode='22023';end if;if not accept_interest then update public.partner_interests set status='declined'where id=interest.id;return interest.id;end if;insert into public.chat_channels(gym_id,created_by,name,description,channel_type)values(target_gym_id,auth.uid(),'Partner '||substr(interest.id::text,1,8),'Private partner-request conversation','partner')returning id into channel_id;insert into public.channel_members(gym_id,channel_id,profile_id)values(target_gym_id,channel_id,auth.uid()),(target_gym_id,channel_id,interest.profile_id);update public.partner_interests set status='accepted',conversation_channel_id=channel_id where id=interest.id;update public.partner_requests set status='matched',closed_at=now()where id=request.id;return channel_id;end;$$;
create or replace function public.withdraw_partner_request(target_gym_id uuid,target_request_id uuid)returns uuid language plpgsql security definer set search_path='' as $$begin update public.partner_requests set status='closed',closed_at=now()where id=target_request_id and gym_id=target_gym_id and profile_id=auth.uid()and status in('open','matched')returning id into target_request_id;if target_request_id is null then raise exception'Request not found'using errcode='22023';end if;return target_request_id;end;$$;
create or replace function public.report_partner_request(target_gym_id uuid,target_request_id uuid,report_reason text)returns uuid language plpgsql security definer set search_path='' as $$declare report_id uuid;begin if char_length(trim(report_reason))not between 3 and 1000 or not exists(select 1 from public.partner_requests where id=target_request_id and gym_id=target_gym_id)then raise exception'Report invalid'using errcode='22023';end if;insert into public.partner_request_reports(gym_id,request_id,reporter_id,reason)values(target_gym_id,target_request_id,auth.uid(),trim(report_reason))returning id into report_id;insert into public.audit_logs(gym_id,actor_profile_id,actor_type,action,target_type,target_id,metadata)values(target_gym_id,auth.uid(),'user','partner_request.reported','partner_request',target_request_id,jsonb_build_object('report_id',report_id));return report_id;end;$$;
revoke all on function public.create_partner_request(uuid,timestamptz,timestamptz,text,text,text,text,text),public.get_partner_requests(uuid),public.express_partner_interest(uuid,uuid,text),public.respond_partner_interest(uuid,uuid,boolean),public.withdraw_partner_request(uuid,uuid),public.report_partner_request(uuid,uuid,text)from public,anon;grant execute on function public.create_partner_request(uuid,timestamptz,timestamptz,text,text,text,text,text),public.get_partner_requests(uuid),public.express_partner_interest(uuid,uuid,text),public.respond_partner_interest(uuid,uuid,boolean),public.withdraw_partner_request(uuid,uuid),public.report_partner_request(uuid,uuid,text)to authenticated,service_role;
