-- Prompt 36: enforceable profile privacy, consent and account-rights workflows.
alter table public.profiles add column deactivated_at timestamptz;
create or replace function private.protect_profile_account_state()returns trigger language plpgsql security definer set search_path=''as $$begin if old.deactivated_at is distinct from new.deactivated_at and current_setting('request.jwt.claim.role',true)<>'service_role'and current_setting('app.account_state_change',true)<>'true'then raise insufficient_privilege;end if;return new;end$$;create trigger protect_profile_account_state before update on public.profiles for each row execute function private.protect_profile_account_state();

create table public.profile_privacy_settings(profile_id uuid primary key references public.profiles(id)on delete cascade,public_display_name text check(public_display_name is null or char_length(btrim(public_display_name))between 1 and 80),profile_visibility text not null default'private'check(profile_visibility in('private','gym','public')),social_visibility text not null default'private'check(social_visibility in('private','gym')),allow_search boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create trigger profile_privacy_settings_updated before update on public.profile_privacy_settings for each row execute function public.set_updated_at();alter table public.profile_privacy_settings enable row level security;alter table public.profile_privacy_settings force row level security;create policy profile_privacy_self on public.profile_privacy_settings for select to authenticated using(profile_id=auth.uid());grant select on public.profile_privacy_settings to authenticated;grant all on public.profile_privacy_settings to service_role;
insert into public.profile_privacy_settings(profile_id)select id from public.profiles on conflict do nothing;
create or replace function private.create_profile_privacy_settings()returns trigger language plpgsql security definer set search_path=''as $$begin insert into public.profile_privacy_settings(profile_id)values(new.id)on conflict do nothing;return new;end$$;create trigger create_profile_privacy_settings after insert on public.profiles for each row execute function private.create_profile_privacy_settings();

create table public.consent_records(id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles(id)on delete restrict,consent_type text not null check(consent_type in('community_guidelines','marketing')),version text not null check(char_length(version)between 1 and 80),granted boolean not null,recorded_at timestamptz not null default now(),source text not null default'user'check(source in('user','migration','support')));
create index consent_records_profile_type_idx on public.consent_records(profile_id,consent_type,recorded_at desc);alter table public.consent_records enable row level security;alter table public.consent_records force row level security;create policy consent_records_select_self on public.consent_records for select to authenticated using(profile_id=auth.uid());grant select on public.consent_records to authenticated;grant all on public.consent_records to service_role;
insert into public.consent_records(profile_id,consent_type,version,granted,recorded_at,source)select profile_id,'community_guidelines',version,true,accepted_at,'migration'from public.community_guideline_acceptances;
create or replace function private.record_guideline_consent()returns trigger language plpgsql security definer set search_path=''as $$begin insert into public.consent_records(profile_id,consent_type,version,granted,recorded_at)values(new.profile_id,'community_guidelines',new.version,true,new.accepted_at);return new;end$$;create trigger record_guideline_consent after insert on public.community_guideline_acceptances for each row execute function private.record_guideline_consent();

create table public.account_deletion_requests(id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles(id)on delete restrict,status text not null default'requested'check(status in('requested','reviewing','completed','declined')),reason text check(reason is null or char_length(reason)<=1000),retention_exceptions jsonb not null default'[]'::jsonb check(jsonb_typeof(retention_exceptions)='array'),requested_at timestamptz not null default now(),resolved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index account_deletion_one_open_idx on public.account_deletion_requests(profile_id)where status in('requested','reviewing');create trigger account_deletion_updated before update on public.account_deletion_requests for each row execute function public.set_updated_at();alter table public.account_deletion_requests enable row level security;alter table public.account_deletion_requests force row level security;create policy account_deletion_select_self on public.account_deletion_requests for select to authenticated using(profile_id=auth.uid());grant select on public.account_deletion_requests to authenticated;grant all on public.account_deletion_requests to service_role;

create or replace function private.can_view_profile(target_profile_id uuid)returns boolean language sql stable security definer set search_path=''as $$select target_profile_id=auth.uid()or exists(select 1 from public.gym_memberships target join public.gym_memberships viewer on viewer.gym_id=target.gym_id and viewer.profile_id=auth.uid()and viewer.status='active'left join public.profile_privacy_settings privacy on privacy.profile_id=target.profile_id where target.profile_id=target_profile_id and target.status='active'and((coalesce(privacy.profile_visibility,'private')in('gym','public'))or viewer.role in('owner','staff','route_setter')))$$;
drop policy profiles_select_shared_gym on public.profiles;create policy profiles_select_by_privacy on public.profiles for select to authenticated using(private.can_view_profile(id));

alter function public.search_gym_content(uuid,text,integer)rename to search_gym_content_unfiltered;
revoke all on function public.search_gym_content_unfiltered(uuid,text,integer)from public,anon,authenticated;
create function public.search_gym_content(target_gym_id uuid,search_query text,result_limit integer default 30)returns table(result_kind text,result_id uuid,title text,snippet text,path text,rank real)language sql stable security definer set search_path=''as $$with content as(select result.result_kind,result.result_id,case when result.result_kind='member'then privacy.public_display_name else result.title end title,result.snippet,result.path,result.rank from public.search_gym_content_unfiltered(target_gym_id,search_query,result_limit)result left join public.profile_privacy_settings privacy on result.result_kind='member'and privacy.profile_id=result.result_id where result.result_kind<>'member'or(privacy.allow_search and privacy.profile_visibility in('gym','public')and privacy.public_display_name is not null)),aliases as(select'member'::text,privacy.profile_id,privacy.public_display_name,'Gym member'::text,'/community'::text,greatest(extensions.similarity(lower(privacy.public_display_name),lower(btrim(search_query))),0.01)::real from public.profile_privacy_settings privacy join public.gym_memberships membership on membership.profile_id=privacy.profile_id and membership.gym_id=target_gym_id and membership.status='active'where privacy.allow_search and privacy.profile_visibility in('gym','public')and privacy.public_display_name is not null and lower(privacy.public_display_name)like'%'||lower(btrim(search_query))||'%')select distinct on(combined.result_kind,combined.result_id)combined.*from(select*from content union all select*from aliases)combined order by combined.result_kind,combined.result_id,combined.rank desc limit result_limit$$;
grant execute on function public.search_gym_content(uuid,text,integer)to authenticated;

create or replace function public.save_profile_privacy(public_name text,visibility text,social_access text,searchable boolean,marketing_allowed boolean)returns void language plpgsql security definer set search_path=''as $$begin if auth.uid()is null or visibility not in('private','gym','public')or social_access not in('private','gym')or char_length(btrim(public_name))not between 1 and 80 then raise exception'Invalid privacy settings'using errcode='22023';end if;insert into public.profile_privacy_settings(profile_id,public_display_name,profile_visibility,social_visibility,allow_search)values(auth.uid(),btrim(public_name),visibility,social_access,searchable)on conflict(profile_id)do update set public_display_name=excluded.public_display_name,profile_visibility=excluded.profile_visibility,social_visibility=excluded.social_visibility,allow_search=excluded.allow_search;insert into public.consent_records(profile_id,consent_type,version,granted)values(auth.uid(),'marketing','marketing-v1',marketing_allowed);end$$;
create or replace function public.request_account_deletion(request_reason text)returns uuid language plpgsql security definer set search_path=''as $$declare request_id uuid;begin if auth.uid()is null or char_length(btrim(coalesce(request_reason,'')))>1000 then raise exception'Invalid deletion request'using errcode='22023';end if;insert into public.account_deletion_requests(profile_id,reason)values(auth.uid(),nullif(btrim(request_reason),''))returning id into request_id;return request_id;exception when unique_violation then raise exception'An account deletion request is already open'using errcode='23505';end$$;
create or replace function public.deactivate_my_account(deactivation_reason text)returns void language plpgsql security definer set search_path=''as $$declare membership record;begin if auth.uid()is null or char_length(btrim(deactivation_reason))not between 3 and 500 then raise exception'A deactivation reason is required'using errcode='22023';end if;for membership in select id,gym_id from public.gym_memberships where profile_id=auth.uid()and status='active'loop insert into public.audit_logs(gym_id,actor_profile_id,actor_type,action,target_type,target_id,metadata)values(membership.gym_id,auth.uid(),'user','privacy.account.deactivated','membership',membership.id,jsonb_build_object('reason',btrim(deactivation_reason)));end loop;update public.gym_memberships set status='suspended',suspended_at=now()where profile_id=auth.uid()and status='active';perform set_config('app.account_state_change','true',true);update public.profiles set deactivated_at=now()where id=auth.uid();end$$;
create or replace function public.export_member_subject_data(target_gym_id uuid,target_profile_id uuid)returns jsonb language plpgsql security definer set search_path=''as $$declare result jsonb;begin if not private.has_gym_role(target_gym_id,array['owner'])or not exists(select 1 from public.gym_memberships where gym_id=target_gym_id and profile_id=target_profile_id)then raise insufficient_privilege;end if;select jsonb_build_object('exported_at',now(),'gym_id',target_gym_id,'profile',(select jsonb_build_object('id',id,'display_name',display_name,'pronouns',pronouns,'bio',bio,'locale',locale,'created_at',created_at)from public.profiles where id=target_profile_id),'membership',(select jsonb_build_object('role',role,'status',status,'joined_at',joined_at,'left_at',left_at)from public.gym_memberships where gym_id=target_gym_id and profile_id=target_profile_id),'ascents',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'session_date',session_date,'ascent_type',ascent_type,'attempts',attempts,'notes',notes,'visibility',visibility,'route_name',route_name_snapshot)),'[]'::jsonb)from public.ascent_logs where gym_id=target_gym_id and profile_id=target_profile_id),'waiver_references',(select coalesce(jsonb_agg(jsonb_build_object('acceptance_id',acceptance.id,'accepted_at',acceptance.accepted_at,'retention_until',acceptance.retention_until,'version_id',acceptance.waiver_version_id)),'[]'::jsonb)from public.waiver_acceptances acceptance where acceptance.gym_id=target_gym_id and acceptance.profile_id=target_profile_id),'community_content',(select jsonb_build_object('post_ids',coalesce(jsonb_agg(id)filter(where kind='post'),'[]'::jsonb),'comment_ids',coalesce(jsonb_agg(id)filter(where kind='comment'),'[]'::jsonb))from(select id,'post'kind from public.community_posts where gym_id=target_gym_id and author_id=target_profile_id union all select id,'comment'from public.comments where gym_id=target_gym_id and author_id=target_profile_id)content))into result;insert into public.audit_logs(gym_id,actor_profile_id,actor_type,action,target_type,target_id,metadata)values(target_gym_id,auth.uid(),'user','privacy.subject_export.created','profile',target_profile_id,'{}');return result;end$$;
revoke all on function public.save_profile_privacy(text,text,text,boolean,boolean),public.request_account_deletion(text),public.deactivate_my_account(text),public.export_member_subject_data(uuid,uuid)from public,anon;grant execute on function public.save_profile_privacy(text,text,text,boolean,boolean),public.request_account_deletion(text),public.deactivate_my_account(text),public.export_member_subject_data(uuid,uuid)to authenticated;
