-- Prompt 30: idempotent Stripe B2B gym subscription projection.
create table public.stripe_billing_events(id text primary key check(id~'^evt_[A-Za-z0-9]+$'),gym_id uuid references public.gyms(id)on delete restrict,event_type text not null,livemode boolean not null,processed_at timestamptz not null default now(),created_at timestamptz not null default now());
create index stripe_billing_events_gym_time_idx on public.stripe_billing_events(gym_id,processed_at desc);
alter table public.stripe_billing_events enable row level security;alter table public.stripe_billing_events force row level security;create policy stripe_billing_events_service_only on public.stripe_billing_events for select to authenticated using(false);revoke all on public.stripe_billing_events from anon,authenticated;grant all on public.stripe_billing_events to service_role;

create or replace function public.upsert_stripe_billing_customer(target_gym_id uuid,customer_id text,billing_address text)returns uuid language plpgsql security definer set search_path=''as $$declare result_id uuid;begin if current_setting('request.jwt.claim.role',true)<>'service_role'or customer_id!~'^cus_[A-Za-z0-9]+$'then raise insufficient_privilege;end if;insert into public.billing_customers(gym_id,stripe_customer_id,billing_email)values(target_gym_id,customer_id,nullif(lower(btrim(billing_address)),''))on conflict(gym_id)do update set stripe_customer_id=excluded.stripe_customer_id,billing_email=excluded.billing_email returning id into result_id;return result_id;end$$;
create or replace function public.apply_stripe_subscription_event(event_id text,event_type text,event_livemode boolean,customer_id text,subscription_id text,price_id text,subscription_status text,period_start timestamptz,period_end timestamptz,cancel_period_end boolean,cancelled_at timestamptz,trial_end timestamptz,plan_name text)returns boolean language plpgsql security definer set search_path=''as $$declare customer public.billing_customers;local_status text;begin if current_setting('request.jwt.claim.role',true)<>'service_role'or event_id!~'^evt_[A-Za-z0-9]+$'or customer_id!~'^cus_[A-Za-z0-9]+$'or subscription_id!~'^sub_[A-Za-z0-9]+$'or price_id!~'^price_[A-Za-z0-9]+$'or plan_name!~'^[a-z][a-z0-9_-]*$'then raise insufficient_privilege;end if;select*into customer from public.billing_customers where stripe_customer_id=customer_id;if customer.id is null then raise exception'Unknown gym billing customer';end if;insert into public.stripe_billing_events(id,gym_id,event_type,livemode)values(event_id,customer.gym_id,event_type,event_livemode)on conflict(id)do nothing;if not found then return false;end if;local_status:=case when subscription_status in('trialing','active','past_due','paused','canceled','unpaid','incomplete')then subscription_status when subscription_status='incomplete_expired'then'canceled'else'incomplete'end;insert into public.subscriptions(gym_id,billing_customer_id,stripe_subscription_id,stripe_price_id,plan_key,status,current_period_start,current_period_end,cancel_at_period_end,canceled_at,trial_ends_at,last_stripe_event_id)values(customer.gym_id,customer.id,subscription_id,price_id,plan_name,local_status,period_start,period_end,cancel_period_end,cancelled_at,trial_end,event_id)on conflict(stripe_subscription_id)do update set stripe_price_id=excluded.stripe_price_id,plan_key=excluded.plan_key,status=excluded.status,current_period_start=excluded.current_period_start,current_period_end=excluded.current_period_end,cancel_at_period_end=excluded.cancel_at_period_end,canceled_at=excluded.canceled_at,trial_ends_at=excluded.trial_ends_at,last_stripe_event_id=excluded.last_stripe_event_id;insert into public.audit_logs(gym_id,actor_type,action,target_type,metadata)values(customer.gym_id,'system','billing.subscription.updated','subscription',jsonb_build_object('event_id',event_id,'status',local_status,'plan',plan_name));return true;end$$;
revoke all on function public.upsert_stripe_billing_customer(uuid,text,text),public.apply_stripe_subscription_event(text,text,boolean,text,text,text,text,timestamptz,timestamptz,boolean,timestamptz,timestamptz,text)from public,anon,authenticated;
grant execute on function public.upsert_stripe_billing_customer(uuid,text,text),public.apply_stripe_subscription_event(text,text,boolean,text,text,text,text,timestamptz,timestamptz,boolean,timestamptz,timestamptz,text)to service_role;
